(function (name, definition, context) {if (typeof context['module'] !== 'undefined' && context['module']['exports']) {context['module']['exports'] = definition.apply(context);}else if (typeof context['define'] !== 'undefined' && context['define'] === 'function' && context['define']['amd']) {define(name, [], definition);}else {context[name] = definition();}})('ydn', function () {var l,q=this;function r(a){return void 0!==a}
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return"array"==aa(a)}function w(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function ba(a){return"boolean"==typeof a}function z(a){return"number"==typeof a}function ca(a){return"function"==aa(a)}function B(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var da="closure_uid_"+(1E9*Math.random()>>>0),ea=0;
function fa(a,b,c){return a.call.apply(a.bind,arguments)}function ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ha(a,b,c){ha=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return ha.apply(null,arguments)}
function ia(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ja=Date.now||function(){return+new Date};function ka(a,b){var c=a.split("."),d=q;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&r(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function C(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ib=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};function ma(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function na(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function oa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,oa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}C(oa,Error);oa.prototype.name="CustomError";function pa(a){for(var b=0;1>b;b++)if('"'==a.charAt(0)&&'"'==a.charAt(a.length-1))return a.substring(1,a.length-1);return a}var qa={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},ra={"'":"\\'"};
function sa(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=c+1,g;if(!(g=qa[d])){if(!(31<e&&127>e))if(d in ra)d=ra[d];else if(d in qa)d=ra[d]=qa[d];else{e=d;g=d.charCodeAt(0);if(31<g&&127>g)e=d;else{if(256>g){if(e="\\x",16>g||256<g)e+="0"}else e="\\u",4096>g&&(e+="0");e+=g.toString(16).toUpperCase()}d=ra[d]=e}g=d}b[f]=g}b.push('"');return b.join("")};var ta=Array.prototype,ua=ta.indexOf?function(a,b,c){return ta.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(x(a))return x(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},va=ta.map?function(a,b,c){return ta.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=x(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},wa=ta.some?function(a,b,c){return ta.some.call(a,b,c)}:function(a,b,c){for(var d=
a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function xa(a,b){var c=ya(a,b,void 0);return 0>c?null:x(a)?a.charAt(c):a[c]}function ya(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1}function za(a){if(!t(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0}function Aa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Ba(a,b,c){return 2>=arguments.length?ta.slice.call(a,b):ta.slice.call(a,b,c)}function Ca(a,b){if(!w(a)||!w(b)||a.length!=b.length)return!1;for(var c=a.length,d=Da,e=0;e<c;e++)if(!d(a[e],b[e]))return!1;return!0}function Da(a,b){return a===b};var Ea;a:{var Fa=q.navigator;if(Fa){var Ga=Fa.userAgent;if(Ga){Ea=Ga;break a}}Ea=""};function Ha(a,b){for(var c=w(b),d=c?b:arguments,c=c?0:1;c<d.length&&(a=a[d[c]],r(a));c++);return a}function Ia(a){var b=arguments.length;if(1==b&&t(arguments[0]))return Ia.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};function Ja(a){q.setTimeout(function(){throw a;},0)}var Ka;
function La(){var a=q.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=ha(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},
this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==Ea.indexOf("Trident")&&-1==Ea.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(r(c.next)){c=c.next;var a=c.Ra;c.Ra=null;a()}};return function(a){d.next={Ra:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){q.setTimeout(a,0)}};function Ma(a,b){Na||Oa();Pa||(Na(),Pa=!0);Qa.push(new Ra(a,b))}var Na;function Oa(){if(q.Promise&&q.Promise.resolve){var a=q.Promise.resolve();Na=function(){a.then(Sa)}}else Na=function(){var a=Sa;!ca(q.setImmediate)||q.Window&&q.Window.prototype.setImmediate==q.setImmediate?(Ka||(Ka=La()),Ka(a)):q.setImmediate(a)}}var Pa=!1,Qa=[];function Sa(){for(;Qa.length;){var a=Qa;Qa=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Ja(d)}}}Pa=!1}function Ra(a,b){this.a=a;this.b=b};function Ta(a,b){this.b=Ua;this.h=void 0;this.a=this.c=null;this.f=this.g=!1;try{var c=this;a.call(b,function(a){Va(c,Wa,a)},function(a){Va(c,Xa,a)})}catch(d){Va(this,Xa,d)}}var Ua=0,Wa=2,Xa=3;Ta.prototype.then=function(a,b,c){return Ya(this,ca(a)?a:null,ca(b)?b:null,c)};ma(Ta);function Za(a){a.b==Ua&&Ma(function(){var a=new $a(void 0);ab(this,a)},a)}
function ab(a,b){if(a.b==Ua)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.fa)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(c.b==Ua&&1==d?ab(c,b):(d=c.a.splice(e,1)[0],bb(c,d,Xa,b)))}}else Va(a,Xa,b)}function cb(a,b){a.a&&a.a.length||a.b!=Wa&&a.b!=Xa||db(a);a.a||(a.a=[]);a.a.push(b)}
function Ya(a,b,c,d){var e={fa:null,Za:null,$a:null};e.fa=new Ta(function(a,g){e.Za=b?function(c){try{var e=b.call(d,c);a(e)}catch(m){g(m)}}:a;e.$a=c?function(b){try{var e=c.call(d,b);!r(e)&&b instanceof $a?g(b):a(e)}catch(m){g(m)}}:g});e.fa.c=a;cb(a,e);return e.fa}Ta.prototype.i=function(a){this.b=Ua;Va(this,Wa,a)};Ta.prototype.j=function(a){this.b=Ua;Va(this,Xa,a)};
function Va(a,b,c){if(a.b==Ua){if(a==c)b=Xa,c=new TypeError("Promise cannot resolve to itself");else{if(na(c)){a.b=1;c.then(a.i,a.j,a);return}if(B(c))try{var d=c.then;if(ca(d)){eb(a,c,d);return}}catch(e){b=Xa,c=e}}a.h=c;a.b=b;db(a);b!=Xa||c instanceof $a||fb(a,c)}}function eb(a,b,c){function d(b){f||(f=!0,a.j(b))}function e(b){f||(f=!0,a.i(b))}a.b=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function db(a){a.g||(a.g=!0,Ma(a.m,a))}
Ta.prototype.m=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)bb(this,a[b],this.b,this.h)}this.g=!1};function bb(a,b,c,d){if(c==Wa)b.Za(d);else{if(b.fa)for(;a&&a.f;a=a.c)a.f=!1;b.$a(d)}}function fb(a,b){a.f=!0;Ma(function(){a.f&&gb.call(null,b)})}var gb=Ja;function $a(a){oa.call(this,a)}C($a,oa);$a.prototype.name="cancel";/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function D(a,b){this.j=[];this.U=b||null;this.b=this.c=!1;this.g=void 0;this.da=this.H=this.m=!1;this.i=0;this.f=null;this.B=0}l=D.prototype;l.la=function(a,b){this.m=!1;hb(this,a,b)};function hb(a,b,c){a.c=!0;a.g=c;a.b=!b;a.Da()}function mb(a){if(a.c){if(!a.da)throw new nb;a.da=!1}}l.callback=function(a){mb(this);hb(this,!0,a)};l.l=function(a){mb(this);hb(this,!1,a)};l.A=function(a,b){return ob(this,a,null,b)};l.Pa=function(a,b){return ob(this,null,a,b)};l.Oa=function(a,b){return ob(this,a,a,b)};
function ob(a,b,c,d){a.j.push([b,c,d]);a.c&&a.Da();return a}l.then=function(a,b,c){var d,e,f=new Ta(function(a,b){d=a;e=b});ob(this,d,function(a){e(a)});return f.then(a,b,c)};ma(D);D.prototype.xa=function(a){ob(this,a.callback,a.l,a);return this};function pb(a,b){b instanceof D?a.A(ha(b.X,b)):a.A(function(){return b})}D.prototype.X=function(a){var b=new D;this.xa(b);a&&(b.f=this,this.B++);return b};function qb(a){return wa(a.j,function(a){return ca(a[1])})}
D.prototype.Da=function(){this.i&&this.c&&qb(this)&&(rb(this.i),this.i=0);this.f&&(this.f.B--,delete this.f);for(var a=this.g,b=!1,c=!1;this.j.length&&!this.m;){var d=this.j.shift(),e=d[0],f=d[1],d=d[2];if(e=this.b?f:e)try{var g=e.call(d||this.U,a);r(g)&&(this.b=this.b&&(g==a||g instanceof Error),this.g=a=g);na(a)&&(this.m=c=!0)}catch(h){a=h,this.b=!0,qb(this)||(b=!0)}}this.g=a;c&&(c=ha(this.la,this,!0),g=ha(this.la,this,!1),a instanceof D?(ob(a,c,g),a.H=!0):a.then(c,g));b&&(a=new sb(a),tb[a.oa]=
a,this.i=a.oa)};function nb(){oa.call(this)}C(nb,oa);nb.prototype.message="Deferred has already fired";nb.prototype.name="AlreadyCalledError";function sb(a){this.oa=q.setTimeout(ha(this.b,this),0);this.a=a}sb.prototype.b=function(){delete tb[this.oa];window.console.error(this.a.stack);throw this.a;};var tb={};function rb(a){var b=tb[a];b&&(q.clearTimeout(b.oa),delete tb[a])};Ia("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var ub=-1!=Ea.indexOf("Opera")||-1!=Ea.indexOf("OPR"),vb=-1!=Ea.indexOf("Trident")||-1!=Ea.indexOf("MSIE"),wb=-1!=Ea.indexOf("Gecko")&&-1==Ea.toLowerCase().indexOf("webkit")&&!(-1!=Ea.indexOf("Trident")||-1!=Ea.indexOf("MSIE")),xb=-1!=Ea.toLowerCase().indexOf("webkit");
(function(){var a="",b;if(ub&&q.opera)return a=q.opera.version,ca(a)?a():a;wb?b=/rv\:([^\);]+)(\)|;)/:vb?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:xb&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Ea))?a[1]:"");return vb&&(b=(b=q.document)?b.documentMode:void 0,b>parseFloat(a))?String(b):a})();function yb(){}function zb(){};function E(a){oa.call(this,a);this.name="ydn.error.ArgumentException"}C(E,oa);function Ab(a){oa.call(this,a);this.name="ydn.error.NotSupportedException"}C(Ab,oa);function Bb(a){oa.call(this,a);this.name="ydn.error.InvalidOperationException"}C(Bb,oa);function Cb(a){Error.captureStackTrace?Error.captureStackTrace(this,Cb):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.InternalError"}C(Cb,Error);Cb.prototype.name="ydn.error.InternalError";function Db(a,b){D.call(this,0,b);this.h=[]}C(Db,D);l=Db.prototype;l.Qa=function(a,b){this.h.push([a,b]);return this};function Eb(a,b){for(var c=0;c<a.h.length;c++)a.h[c][0].call(a.h[c][1],b)}l.callback=function(a){this.h.length=0;Db.D.callback.call(this,a)};l.l=function(a){this.h.length=0;Db.D.l.call(this,a)};l.xa=function(a){Db.D.xa.call(this,a);a instanceof Db&&a.Qa(function(a){Eb(this,a)},this);return this};l.zb=function(){return this};var Fb={READ_ONLY:"readonly",READ_WRITE:"readwrite",VERSION_CHANGE:"versionchange"},Gb=Fb.READ_ONLY,F=Fb.READ_WRITE,Hb=Fb.VERSION_CHANGE,G=q.indexedDB||q.mozIndexedDB||q.webkitIndexedDB||q.moz_indexedDB||q.msIndexedDB;D.prototype.done=D.prototype.A;D.prototype.fail=D.prototype.Pa;D.prototype.always=D.prototype.Oa;Db.prototype.then=Db.prototype.then;function Ib(a,b){var c,d;2==arguments.length&&x(arguments[1])?(c=!0,d=arguments[1].split(".")):d=(c=w(b))?b:arguments;for(c=c?0:1;c<d.length&&(a=a[d[c]],r(a));c++);return a}function Jb(a,b,c){if(a)if(-1==b.indexOf("."))a[b]=c;else{b=b.split(".");for(var d=b.pop(),e;e=b.shift();)B(a[e])||(a[e]={}),a=a[e];a[d]=c}}var Kb={};
function Lb(a){var b=[a];a=new Mb;for(var c=0,d,e;void 0!==(e=b.pop());){0===c%4&&12<c+4&&(a.write(c),c=0);d=typeof e;if(e instanceof Array)if(c+=4,0<e.length){b.push(Kb);for(d=e.length;d--;)b.push(e[d]);continue}else a.write(c);else if("number"===d)c+=1,a.write(c),Nb(a,e);else if(e instanceof Date)c+=2,a.write(c),Nb(a,e.valueOf());else if("string"===d){c+=3;a.write(c);c=a;for(d=0;d<e.length;d++){var f=e.charCodeAt(d);126>=f?c.write(f+1):16510>=f?(f-=127,c.write(128|f>>8,f&255)):c.write(192|f>>10,
f>>2|255,(f|3)<<6)}c.write(0)}else if(e===Kb)a.write(0);else return"";c=0}for(b=a.a.length;"00"===a.a[--b];);a.a.length=++b;return a.toString()}
function Nb(a,b){var c,d,e;c=b;var f=e=d=0;if(0!==c)if(isFinite(c)){0>c&&(d=1,c=-c);f=0;if(2.2250738585072014E-308<=c){for(e=c;1>e;)f--,e*=2;for(;2<=e;)f++,e/=2;e=f+1023}f=e?Math.floor(4503599627370496*(c/Math.pow(2,f)-1)):Math.floor(c/4.9E-324)}else e=2047,isNaN(c)?f=0x8000000000000:-Infinity===c&&(d=1);c=d;d=e;e=f;c&&(e=0xfffffffffffff-e,d=2047-d);a.write((c?0:128)|d>>4);a.write((d&15)<<4|0|e/281474976710656);e%=281474976710656;c=0|e/4294967296;a.write(c>>8,c&255);e%=4294967296;c=0|e/65536;a.write(c>>
8,c&255);c=e%65536;a.write(c>>8,c&255)}function Ob(a){var b=Pb(a)|0,c=b>>7?!1:!0,d=c?-1:1,e=(b&127)<<4,b=Pb(a)|0,e=e+(b>>4);c&&(e=2047-e);for(var b=[c?15-(b&15):b&15],f=6;f--;)b.push(c?255-(Pb(a)|0):Pb(a)|0);a=0;for(f=7;f--;)a=a/256+b[f];a/=16;return 0===a&&0===e?0:(a+1)*Math.pow(2,e-1023)*d}
function Qb(a){for(var b=[],c=0,d=0,e=0,f,g;;){f=Pb(a);if(0===f||null==f)break;0===c?(g=f>>6,2>g&&!isNaN(f)?b.push(String.fromCharCode(f-1)):(c=g,d=f<<10,e++)):2===c?(b.push(String.fromCharCode(d+f+127)),c=d=e=0):2===e?(d+=f<<2,e++):(b.push(String.fromCharCode(d|f>>6)),c=d=e=0)}return b.join("")}function Rb(a){this.a=null;this.b=a;this.c=this.b.length-1;this.index=-1}function Pb(a){return a.a=a.index<a.c?parseInt(a.b.charAt(++a.index)+a.b.charAt(++a.index),16):null}
function Mb(){this.a=[];this.b=void 0}Mb.prototype.write=function(a){for(var b=0;b<arguments.length;b++)this.b=arguments[b].toString(16),this.a.push(2===this.b.length?this.b:this.b="0"+this.b)};Mb.prototype.toString=function(){return this.a.length?this.a.join(""):""};function Sb(a,b){var c=Lb(a),d=Lb(b);return c>d?1:c==d?0:-1};function H(a,b,c){Db.call(this,0,c);this.v=a;this.h=[];this.s=[];this.ea=[];this.a=null;this.Z="";this.K=0}C(H,Db);l=H.prototype;l.Z="";l.logger=null;function Tb(a,b,c){a.a=b;a.Z=c;if(b){for(c=0;c<a.s.length;c++)a.s[c][0].call(a.s[c][1],b);a.s.length=0}}function Ub(a){var b=new H(a.v);a.K++;Tb(b,a.a,a.Z+"C"+a.K);return b}l.qb=function(){return!!this.a};
l.abort=function(){if(this.a)if(ca(this.a.abort))this.a.abort();else if(ca(this.a.executeSql))this.a.executeSql("ABORT",[],function(){},function(){return!0});else throw new Ab;else throw new Vb("");};function I(a,b,c){var d=a.ea.shift();c=!!c;d?d[0].call(d[1],b,c,function(b,c){I(a,b,c)}):c?a.l(b):a.callback(b)}function Wb(a,b,c){a.ea.push([b,c])}function J(a,b,c){a.a?b.call(c,a.a):a.s.push([b,c])}l.callback=function(a){H.D.callback.call(this,a)};l.l=function(a){H.D.l.call(this,a)};
function Xb(a){var b="";a.Z&&(b=a.a?"*":"",b="["+a.Z+b+"]");return a.v+b}function Yb(a,b){var c=new H(a);I(c,b);return c}l.toString=function(){return"Request:"+Xb(this)};
l.Da=function(){this.i&&this.c&&qb(this)&&(rb(this.i),this.i=0);this.f&&(this.f.B--,delete this.f);for(var a=this.g,b=!1;this.j.length&&!this.m;){var c=this.j.shift(),d=c[0],e=c[1],c=c[2];if(d=this.b?e:d)d=d.call(c||this.U,a),r(d)&&(this.b=this.b&&(d==a||d instanceof Error),this.g=a=d),na(a)&&(this.m=b=!0)}this.g=a;b&&(b=ha(this.la,this,!0),d=ha(this.la,this,!1),a instanceof D?(ob(a,b,d),a.H=!0):a.then(b,d))};
l.toJSON=function(){var a=(this.Z||"").match(/B(\d+)T(\d+)(?:Q(\d+?))?(?:R(\d+))?/)||[];return{method:this.v?this.v.split(":"):[],branchNo:parseFloat(a[1]),transactionNo:parseFloat(a[2]),queueNo:parseFloat(a[3]),requestNo:parseFloat(a[4])}};var K=G&&G.cmp?ha(G.cmp,G):Sb,Zb=[];var $b;$b=!1;var ac=Ea;ac&&(-1!=ac.indexOf("Firefox")||-1!=ac.indexOf("Camino")||-1!=ac.indexOf("iPad")||-1!=ac.indexOf("iPhone")||-1!=ac.indexOf("iPod")||-1!=ac.indexOf("Chrome")||-1!=ac.indexOf("Android")||-1!=ac.indexOf("Safari")&&($b=!0));var bc=$b;function cc(){0!=dc&&(this[da]||(this[da]=++ea));this.da=this.da;this.ob=this.ob}var dc=0;cc.prototype.da=!1;function ec(a,b){this.type=a;this.target=b}ec.prototype.preventDefault=function(){};function fc(a,b){ec.call(this,a,b)}C(fc,ec);fc.prototype.a=function(){return this.b};function gc(a,b,c,d,e){ec.call(this,a,b);this.version=c;this.lb=d;this.Ya=e}C(gc,fc);l=gc.prototype;l.name="ReadyEvent";l.version=NaN;l.lb=NaN;l.Ya=null;l.Gb=function(){return this.version};l.tb=function(){return this.lb};l.sb=function(){return this.Ya};function hc(a,b,c){ec.call(this,c||"error",a);this.error=b}C(hc,fc);hc.prototype.toString=function(){return this.name+":"+(this.error?this.error:"")};
hc.prototype.name="ErrorEvent";hc.prototype.error=null;hc.prototype.c=function(){return this.error};function ic(a,b){hc.call(this,a,b,"fail")}C(ic,hc);ic.prototype.name="FailEvent";function jc(a,b,c){var d;if(B(a))d=a.store,b=a.id,null!=a.parent&&(c=new jc(a.parent));else if(r(b))d=a;else if(d=a.lastIndexOf("^|"),b=a,0<d&&(b=a.substr(d),c=new jc(a.substring(0,d))),b=b.split("^:"),d=b[0],b=b[1],!r(b))throw Error("Invalid key value: "+a);this.b=d;this.a=b;this.c=c||null}l=jc.prototype;l.toJSON=function(){var a={store:this.b,id:this.a};this.c&&(a.parent=this.c.toJSON());return a};l.valueOf=function(){return(this.c?this.c.valueOf()+"^|":"")+this.b+"^:"+this.a};
l.toString=function(){return this.valueOf().replace("^|","|").replace("^:",":")};l.Bb=function(){return this.b};l.rb=function(){return this.a};function kc(a){return t(a.a)?a.a.join("^|"):a.a instanceof Date?+a.a:a.a}l.Ab=function(){return this.c};function lc(a){if(w(a)){for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}return a};function L(a,b,c,d){a>b&&(b=a=void 0);null===a&&(a=void 0);null===b&&(b=void 0);this.lower=a;this.upper=b;this.lowerOpen=!!c;this.upperOpen=!!d}L.prototype.lower=void 0;L.prototype.upper=void 0;L.prototype.toJSON=function(){var a;a=this||{};return{lower:a.lower,upper:a.upper,lowerOpen:a.lowerOpen,upperOpen:a.upperOpen}};function mc(a){return nc(a)}function oc(a){return new L(a,a,!1,!1)}function pc(a,b,c,d){return new L(a,b,c,d)}function qc(a,b){return new L(void 0,a,void 0,!!b)}
function rc(a,b){return new L(a,void 0,!!b,void 0)}function sc(a){var b;if(t(a))b=Aa(a),b.push("\uffff");else if(x(a))b=a+"\uffff";else if(z(a))b=a+2.220460492503131E-16,a-=2.220460492503131E-16;else return oc(a);return pc(a,b,!1,!0)}function nc(a){return null!=a?null!=a.upper&&null!=a.lower?tc.bound(a.lower,a.upper,!!a.lowerOpen,!!a.upperOpen):null!=a.upper?tc.upperBound(a.upper,a.upperOpen):null!=a.lower?tc.lowerBound(a.lower,a.lowerOpen):null:null}
function uc(a,b){var c=a.lower,d=a.upper,e=a.lowerOpen,f=a.upperOpen;null!=b.lower&&(null==a.lower||b.lower>=a.lower)&&(c=b.lower,e=b.lowerOpen||a.lowerOpen);null!=b.upper&&(null==a.upper||b.upper<=a.upper)&&(d=b.upper,f=b.upperOpen||a.upperOpen);return pc(c,d,e,f)}
function vc(a,b,c,d,e){if(c)if(c.lowerOpen||c.upperOpen||null==c.lower||null==c.upper||0!==K(c.lower,c.upper)){if(null!=c.lower){var f=c.lowerOpen?" > ":" >= ";d.push(a+f+"?");e.push(wc(c.lower,b))}null!=c.upper&&(f=c.upperOpen?" < ":" <= ",d.push(a+f+"?"),e.push(wc(c.upper,b)))}else d.push(a+" = ?"),e.push(wc(c.lower,b))}
function xc(a,b,c,d){var e,f,g,h;if("starts"==a||"^"==a)return sc(b);if("<"==a||"<="==a)e=b,g="<"==a;else if(">"==a||">="==a)f=b,h=">"==a;else if("="==a||"=="==a)e=f=b;else throw new E("invalid op: "+a);if("<"==c||"<="==c)e=d,g="<"==c;else if(">"==c||">="==c)f=d,h=">"==c;else if(r(c))throw new E("invalid op2: "+c);return pc(f,e,h,g)}var tc=q.IDBKeyRange||q.webkitIDBKeyRange||L;function yc(a,b,c,d,e,f){r(e)||(e=t(a)?a.join(", "):a);if(null!=a&&!x(a)&&!w(a))throw new E("index keyPath for "+e+" must be a string or array, but "+a+" is "+typeof a);!r(a)&&r(e)&&(a=e);this.keyPath=a;this.h=w(this.keyPath);this.a=e;this.type=zc(b);if(r(b)){if(!r(this.type))throw new E("type invalid in index: "+this.a);if(t(this.keyPath))throw new E('composite key for store "'+this.a+'" must not specified type');}this.unique=!!c;this.multiEntry=!!d;this.i=x(this.type)?this.type:Ac;this.f=x(e)?e:
t(a)?this.keyPath.join(","):a;this.c=sa(this.f);this.b=this.h?null:this.keyPath.split(".");this.g=f||null}var Ac="TEXT";function wc(a,b){if("DATE"==b){if(a instanceof Date)return+a}else return null!=b?a:Lb(a)}
function Bc(a,b){var c;if("DATE"==b)c=new Date(a);else if(r(b))c=a;else{for(var d=c=[],e,f=[],g,h,k=new Rb(a);null!=Pb(k);)if(0===k.a)d=f.pop();else{if(null===k.a)break;do{g=k.a/4|0;e=k.a%4;for(var m=0;m<g;m++)h=[],d.push(h),f.push(d),d=h;if(0===e&&12<k.a+4)Pb(k);else break}while(1);1===e?d.push(Ob(k)):2===e?d.push(new Date(Ob(k))):3===e?d.push(Qb(k)):0===e&&(d=f.pop())}c=c[0]}return c}var Cc=["BLOB","DATE","INTEGER","NUMERIC",Ac];function zc(a){if(x(a))return a=ua(Cc,a),Cc[a]}
yc.prototype.getName=function(){return this.a};yc.prototype.toJSON=function(){return{name:this.a,keyPath:this.keyPath,type:this.type,unique:this.unique,multiEntry:this.multiEntry}};yc.prototype.clone=function(){var a=t(this.keyPath)?Aa(this.keyPath):this.keyPath;return new yc(a,this.type,this.unique,this.multiEntry,this.a,this.g)};
function Dc(a,b){return null!=a||null!=b?null!=a?null!=b?w(a)&&w(b)?Ca(a,b)?null:"expect: "+a+", but: "+b:Ec(a,b)?null:"expect: "+a+", but: "+b:"keyPath: "+a+" no longer defined":"newly define "+b:null}yc.prototype.hint=function(a){if(!a)return this;var b=t(this.keyPath)?Aa(this.keyPath):this.keyPath,c=this.type;r(a.type)||"TEXT"!=c||(c=void 0);return new yc(b,c,this.unique,this.multiEntry,a.a)};function Fc(a,b,c,d,e,f,g){if(!x(a))throw new E("store name must be a string");this.f=a;this.keyPath=r(b)?b:null;this.i=w(this.keyPath);if(null!==this.keyPath&&!x(this.keyPath)&&!this.i)throw new E("keyPath must be a string or array");this.b=!!c;var h;if(null!=d){h=zc(d);if(!r(h))throw new E('type "'+d+'" for primary key in store "'+this.f+'" is invalid.');if(this.i)throw new E('composite key for store "'+this.f+'" must not specified type');}this.type=null!=h?h:this.b?"INTEGER":void 0;this.h=x(this.keyPath)?
this.keyPath.split("."):[];this.a=e||[];a=[];for(b=0;b<this.a.length;b++){c=this.a[b].getName();if(0<=a.indexOf(c))throw new E('index "'+c+'" already defined in store: '+this.f);a.push(c)}this.M=!!f;this.W=!!g;this.m=x(this.type)?this.type:Ac;this.g=t(this.keyPath)?this.keyPath.join(","):x(this.keyPath)?this.keyPath:"_ROWID_";this.c=sa(this.g);this.j=[]}l=Fc.prototype;l.M=!1;l.W=!1;
l.toJSON=function(){for(var a=[],b=0;b<this.a.length;b++)a.push(this.a[b].toJSON());return{name:this.f,keyPath:this.keyPath,autoIncrement:this.b,type:this.type,indexes:a}};
function Gc(a){var b=[],c=a.indexes||[];if(t(c))for(var d=0;d<c.length;d++){var e;e=c[d];e=new yc(e.keyPath,e.type,e.unique,e.multiEntry,e.name,e.generator);r(e.keyPath)&&e.keyPath===a.keyPath||b.push(e)}return new Fc(a.name,a.keyPath,a.autoIncrement,"undefined"===a.type||"null"===a.type?void 0:a.type,b,a.dispatchEvents,a.fixed)}
function Hc(a,b,c,d,e,f,g){a=Ic(a,b,c,d,e,f,g);b="";0!=c&&(b+="SELECT "+a.select);b+=" FROM "+a.I;a.o&&(b+=" WHERE "+a.o);a.group&&(b+=" GROUP BY "+a.group);a.J&&(b+=" ORDER BY "+a.J);return b}
function Ic(a,b,c,d,e,f,g){var h={select:"",I:"",o:"",group:"",J:""},k=a.g,m=a.c,p=null;d!==k&&x(d)&&(p=Jc(a,d));var n=!!p,u=d||k,v=sa(u),y=n?p.type:a.type,A=n&&p.multiEntry;h.I=M(a);6===c?h.select="COUNT("+m+")":3===c||1===c||2===c?(h.select=m,null!=d&&d!=k&&(h.select+=", "+v)):h.select="*";d=g?"DISTINCT ":"";k=[];A?(A=sa("ydn.db.me:"+a.getName()+":"+p.getName()),h.select=6===c?"COUNT("+d+A+"."+v+")":3===c||1===c||2===c?"DISTINCT "+M(a)+"."+m+", "+A+"."+v+" AS "+u:"DISTINCT "+M(a)+".*, "+A+"."+v+
" AS "+u,h.I=A+" INNER JOIN "+M(a)+" USING ("+m+")",null!=e&&(vc(A+"."+v,y,e,k,b),0<k.length&&(h.o=h.o?h.o+(" AND "+k.join(" AND ")):k.join(" AND ")))):null!=e&&(vc(v,y,e,k,b),0<k.length&&(h.o=h.o?h.o+(" AND "+k.join(" AND ")):k.join(" AND ")));n&&!p.unique&&g&&(h.group=v);a=f?"DESC":"ASC";h.J=v+" "+a;n&&(h.J+=", "+m+" "+a);return h}
function Kc(a,b,c,d,e,f,g,h,k){var m,p,n,u;null!=e?(m=e.lower,p=e.upper,n=e.lowerOpen,u=e.upperOpen,f?null!=p?(e=K(h,p),-1==e?(p=h,u=k):0==e&&(u=k||u)):(p=h,u=k):null!=m?(e=K(h,m),1==e?(m=h,n=k):0==e&&(n=k||n)):(m=h,n=k)):f?(p=h,u=k):(m=h,n=k);e=new L(m,p,!!n,!!u);d=d?Jc(a,d):null;b=Ic(a,c,b,d?d.f:a.g,e,f,g);b="SELECT "+b.select+" FROM "+b.I+(b.o?" WHERE "+b.o:"")+(b.group?" GROUP BY "+b.group:"")+" ORDER BY "+b.J;d&&(b+=", "+a.c+(f?"DESC":"ASC"));return b}
function Lc(a,b,c,d,e,f,g,h,k,m){var p=Jc(a,d),n=p.f;d=p.c;var u=a.c,v=k?" <":" >",v=g?v+" ":v+"= ";g=wc(f,p.type);h=wc(h,a.type);p="";e?(a=Ic(a,c,b,n,e,k,m),a.o+=" AND ",p=d+v+"?",c.push(g)):(e=k?qc(f,!0):rc(f,!0),a=Ic(a,c,b,n,e,k,m),p=a.o,a.o="");a.o+="("+p+" OR ("+d+" = ? AND "+u+v+"?))";c.push(g);c.push(h);return"SELECT "+a.select+" FROM "+a.I+" WHERE "+a.o+(a.group?" GROUP BY "+a.group:"")+" ORDER BY "+a.J}l.clone=function(){return Gc(this.toJSON())};l.index=function(a){return this.a[a]||null};
function Jc(a,b){return xa(a.a,function(a){return a.getName()==b})}function Mc(a,b){for(var c=0;c<a.a.length;c++)if(!Dc(a.a[c].keyPath,b))return a.a[c];return null}function Nc(a,b){return b===a.keyPath?!0:wa(a.a,function(a){return a.getName()==b})}function M(a){return sa(a.f)}
function Oc(a,b){if(!b)return a;var c=a.b,d=t(a.keyPath)?Aa(a.keyPath):a.keyPath,e=a.type,f=va(a.a,function(a){return a.clone()});r(b.type)||"TEXT"!=e||(e=void 0);t(b.keyPath)&&x(d)&&d==b.keyPath.join(",")&&(d=Aa(b.keyPath));for(var g=0,h=b.a.length;g<h;g++)if(b.a[g].h)for(var k=b.a[g].getName(),m=f.length-1;0<=m;m--)if(0<=k.indexOf(f[m].getName())){f[m]=b.a[g].clone();break}for(g=0;g<f.length;g++)(h=Jc(b,f[g].getName()))&&(f[g]=f[g].hint(h));return new Fc(b.f,d,c,e,f)}l.getName=function(){return this.f};
function Pc(a){return!!a.keyPath}function Qc(a,b,c){if(b){if(!a.keyPath&&null!=c)return c;if(a.i){c=[];for(var d=0;d<a.keyPath.length;d++)c.push(Ib(b,a.keyPath[d]));return c}if(a.keyPath)return Ha(b,a.h)}}function Rc(a,b,c){for(var d=0;d<a.h.length;d++){var e=a.h[d];if(d==a.h.length-1){b[e]=c;break}r(b[e])||(b[e]={});b=b[e]}}
function Sc(a,b,c){var d=[],e=[];c=r(c)?c:Qc(a,b);r(c)&&(e.push(a.c),d.push(wc(c,a.type)));for(var f=0;f<a.a.length;f++){var g=a.a[f];if(!g.multiEntry&&g.getName()!==a.keyPath&&"_default_"!=g.getName()){var h;h=g;var k=b;if(null!=k)if(w(h.keyPath)){for(var m=[],p=0,n=h.keyPath.length;p<n;p++){var u=Ib(k,h.keyPath[p]);m[p]=u}h=m}else h=Ib(k,h.keyPath);else h=void 0;null!=h&&(d.push(wc(h,g.type)),e.push(g.c))}}a.W?a.W&&!a.keyPath&&0==a.a.length&&(x(b)&&-1==b.indexOf(";base64,")?d.push(b):d.push(P(b)),
e.push("_default_")):(d.push(P(b)),e.push("_default_"));a=[];for(f=d.length-1;0<=f;f--)a[f]="?";return{Ta:e,gb:a,values:d,key:c}}
function Tc(a,b){if(!b)return"missing store: "+a.f;if(a.f!=b.f)return"store name, expect: "+a.f+", but: "+b.f;var c=Dc(a.keyPath,b.keyPath);if(c)return"keyPath, "+c;if(r(a.b)&&r(b.b)&&a.b!=b.b)return"autoIncrement, expect:  "+a.b+", but: "+b.b;if(a.a.length!=b.a.length)return"indexes length, expect:  "+a.a.length+", but: "+b.a.length;if(r(a.type)&&r(b.type)&&(w(a.type)?!Ca(a.type,b.type):a.type!=b.type))return"data type, expect:  "+a.type+", but: "+b.type;for(c=0;c<a.a.length;c++){var d=Jc(b,a.a[c].getName()),
e;e=a.a[c];if(d)if(e.a!=d.a)e="name, expect: "+e.a+", but: "+d.a;else{var f=Dc(e.keyPath,d.keyPath);e=f?"keyPath, "+f:null!=e.unique&&null!=d.unique&&e.unique!=d.unique?"unique, expect: "+e.unique+", but: "+d.unique:null!=e.multiEntry&&null!=d.multiEntry&&e.multiEntry!=d.multiEntry?"multiEntry, expect: "+e.multiEntry+", but: "+d.multiEntry:r(e.type)&&r(d.type)&&(w(e.type)?!Ca(e.type,d.type):e.type!=d.type)?"data type, expect: "+e.type+", but: "+d.type:""}else e="no index for "+e.a;if(0<e.length)return'index "'+
a.a[c].getName()+'" '+e}return""}function Uc(a,b){if(b)for(var c=0;c<a.a.length;c++){var d=a.a[c],e=b;if(d.g){var f=d.g(e),g=typeof f;if("string"==g||"number"==g||f instanceof Date||t(f)){for(g=0;g<d.b.length-1;g++)B(e[d.b[g]])||(e[d.b[g]]={});e[d.b[d.b.length-1]]=f}}}}function S(a,b,c,d,e){for(var f=0;f<a.j.length;f++)d!==f&&a.j[f].call(e,b,c)};function Vc(a){return!x(a)||/^[\s\xa0]*$/.test(a)?{}:JSON.parse(a)}function Wc(a){var b;try{b=P(a)}catch(c){b=""}return b?b.substr(0,70)+(70<b.length?"...":""):""}function P(a){return JSON.stringify(a,void 0,void 0)};function Xc(a){this.a=a};function Yc(a,b){this.name=a;this.a=b}Yc.prototype.getName=function(){return this.name};Yc.prototype.count=function(){return this.a.length};Yc.prototype.index=function(a){return this.a[a]};function Zc(a){if(!t(a.sources))throw new E("indexes require for full text search index "+a.name+", but "+a.sources+" of type "+typeof a.sources+" found.");var b=a.sources.map(function(a){return new Xc(a.storeName)});return new Yc(a.name,b)};function $c(a,b){var c,d,e=b;if(B(a)){d=a;c=d.version;for(var e=[],f=d.stores||[],g=0;g<f.length;g++){var h=Gc(f[g]);e.push(h)}}else x(a)?c=0==a.length?void 0:parseFloat(a):z(a)&&(c=a);if(r(c)){if(!z(c)||0>c)throw new E("Invalid version: "+c+" ("+a+")");isNaN(c)&&(c=void 0)}if(r(b)&&(!t(b)||0<b.length&&!(b[0]instanceof Fc)))throw new E("stores");this.version=c;this.b=!r(this.version);this.stores=e||[];c=[];if(d&&d.fullTextCatalogs)for(g=0;g<d.fullTextCatalogs.length;g++)e=Zc(d.fullTextCatalogs[g]),
c[g]=e,U(this,e.getName())||(f=[new yc("k",Ac),new yc("v",Ac)],e=new Fc(e.getName(),"id",!1,void 0,f,!1,!1),this.stores.push(e));this.c=c}$c.prototype.toJSON=function(){var a=va(this.stores,function(a){return a.toJSON()}),b={};b.stores=a;r(this.version)&&(b.version=this.version);return b};$c.prototype.b=!1;$c.prototype.a=function(){return!1};function ad(a){return va(a.stores,function(a){return a.getName()})}$c.prototype.count=function(){return this.stores.length};
function U(a,b){return xa(a.stores,function(a){return a.getName()==b})}function bd(a,b){return wa(a.stores,function(a){return a.getName()==b})}
function cd(a,b,c,d){if(!b||a.stores.length!=b.stores.length)return"Number of store: "+a.stores.length+" vs "+b.stores.length;for(var e=0;e<a.stores.length;e++){var f=U(b,a.stores[e].getName());if(f){c&&(f=Oc(f,a.stores[e]));if(d)for(var g=f,h=a.stores[e],k=0;k<h.a.length;k++){var m=h.a[k];Nc(g,m.getName())||"BLOB"!=m.type||(m=new yc(m.keyPath,m.type,m.unique,m.multiEntry,m.getName()),g.a.push(m))}f=Tc(a.stores[e],f);if(0<f.length)return'store: "'+a.stores[e].getName()+'" '+f}else return'missing object store "'+
a.stores[e].getName()+'"'}return""};function dd(a,b){$c.call(this,a,b)}C(dd,$c);dd.prototype.a=function(){return!0};function ed(a,b){a.stores.push(b)};function fd(a){Error.captureStackTrace?Error.captureStackTrace(this,fd):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.InternalError"}C(fd,Error);fd.prototype.name="ydn.InternalError";function gd(a){Error.captureStackTrace?Error.captureStackTrace(this,gd):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.ConstraintError"}C(gd,Error);gd.prototype.name="ydn.error.ConstraintError";
function hd(a){Error.captureStackTrace?Error.captureStackTrace(this,hd):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.InvalidOperationException"}function id(a){Error.captureStackTrace?Error.captureStackTrace(this,id):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.error.InvalidOperationError"}C(id,Error);function Ec(a,b){var c;c=c||{};if(null!=a&&null!=b){if(w(a)&&w(b)){if(a.length!=b.length)return!1;for(var d=0;d<a.length;d++)if(-1==ya(b,function(b){return Ec(b,a[d])}))return!1;return!0}if(w(a))return 1==a.length&&Ec(a[0],b);if(w(b))return 1==b.length&&Ec(b[0],a);if(B(a)&&B(a)){for(var e in a)if(a.hasOwnProperty(e)&&!c[e]){var f=Ec(a[e],b[e]);if(!f)return!1}for(e in b)if(b.hasOwnProperty(e)&&!c[e]&&(f=Ec(a[e],b[e]),!f))return!1;return!0}return a===b}return!1};/*
 Copyright 2012 YDN Authors, Yathit. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");.
*/
function V(a,b,c){c=c||{};this.s=c.mechanisms||(bc?Ba(jd,1):jd);this.m=c.size;this.v=r(c.connectionTimeout)?c.connectionTimeout:6E4;this.a=null;this.g=[];this.pa=!1;var d;if(b instanceof $c)d=b;else if(B(b)){c.autoSchema||!r(b.stores)?d=new dd(b):d=new $c(b);var e=b.stores?b.stores.length:0;for(c=0;c<e;c++)U(d,b.stores[c].name)}else d=new dd;this.c=d;for(c=0;c<this.c.count();c++);r(a)&&this.j(a);this.f=new D}V.prototype.logger=null;
V.prototype.B=function(a){if(r(a)){var b=function(b){a(b.toJSON());a=void 0};if(this.a)this.a.R(b);else{var c=this;this.transaction(function(a){c.a.R(b,a)},null,Gb)}}return this.c?this.c.toJSON():null};V.prototype.j=function(a){if(this.a)throw new Bb("Already connected with "+this.h);this.h=a;kd(this)};V.prototype.getName=function(){return this.h};var jd="indexeddb sqlite websql localstorage sessionstorage userdata memory".split(" ");l=V.prototype;l.Ba=function(){return null};
function kd(a){function b(b,e){b?(a.Va=NaN,d.kb=function(){},d.La=function(){a.a=null},d.ab=function(){},setTimeout(function(){ld(a,e);md(a)},10),c.callback(e)):(setTimeout(function(){ld(a,new ic(a,e));if(a.g)for(var b;b=a.g.shift();)b.F&&b.F("error",e)},10),c.l(e))}for(var c=new D,d=null,e=a.s,f=0;f<e.length;f++){var g=e[f].toLowerCase();if(d=a.Ba(g)){d=a.Ba(g);break}}null===d?(e=new gd("No storage mechanism found."),b(!1,new ic(a,e))):ob(d.connect(a.h,a.c),function(a){this.a=d;b(!0,new gc("ready",
this,parseFloat(d.jb()),parseFloat(a),null))},function(a){b(!1,a)},a)}l.Ma=function(){if(this.a)return this.a.ib()};l.sa=function(a,b){this.f.X().Oa(a,b)};function ld(a,b){setTimeout(function(){a.c.b&&a.f.c||(b instanceof hc?a.f.l(b.error):a.f.callback())},4)}function nd(a){return!!a.a&&a.a.Ka()}l.close=function(){this.a&&(this.a.close(),this.a=null)};l.Fb=function(){return this.a?this.a.hb():null};l.Va=NaN;function md(a){var b=a.g.shift();b&&a.transaction(b.na,b.xb,b.mode,b.F);a.Va=ja()}l.pa=!1;
l.transaction=function(a,b,c,d){var e=b;x(b)?e=[b]:null!=b||(e=null);if(this.a&&this.a.Ka()&&!this.pa){var f=this,g=r(c)?c:Gb;g==Hb&&(this.pa=!0);this.a.Ca(function(b){a(b);a=null},e,g,function(a,b){ca(d)&&(d(a,b),d=void 0);g==Hb&&(f.pa=!1);md(f)})}else this.g.push({na:a,xb:e,mode:c,F:d})};V.prototype.close=V.prototype.close;V.prototype.getType=V.prototype.Ma;V.prototype.getName=V.prototype.getName;V.prototype.getSchema=V.prototype.B;V.prototype.onReady=V.prototype.sa;V.prototype.setName=V.prototype.j;V.prototype.transaction=V.prototype.transaction;V.prototype.db=V.prototype.Fb;ka("ydn.db.version","1.3.1");ka("ydn.db.cmp",K);ka("ydn.db.deleteDatabase",function(a,b){for(var c,d=0;d<Zb.length;d++){var e=Zb[d](a,b);e&&(c=e)}return c||Yb("vc",null)});gc.prototype.name=gc.prototype.name;
gc.prototype.getVersion=gc.prototype.Gb;gc.prototype.getOldVersion=gc.prototype.tb;gc.prototype.getOldSchema=gc.prototype.sb;hc.prototype.getError=hc.prototype.c;H.prototype.abort=H.prototype.abort;H.prototype.canAbort=H.prototype.qb;Db.prototype.progress=Db.prototype.Qa;Db.prototype.promise=Db.prototype.zb;ka("ydn.db.KeyRange",L);L.only=oc;L.bound=pc;L.upperBound=qc;L.lowerBound=rc;function od(a,b,c,d){cc.call(this);this.a=c;this.pb=c.getName();this.i=void 0;this.g=!1;this.V=null;this.m=a;this.s=this.j=!1;this.H=d||4;this.X=this.h=this.c=void 0;this.K=function(){throw new Cb;};this.U=function(){throw new Cb;};this.ea=function(){}}C(od,cc);l=od.prototype;
l.Na=function(a,b,c,d,e){r(b)&&(a=this.a,this.i=(t(b)?Mc(a,b):Jc(a,b)).getName());this.g=x(this.i);this.V=c||null;this.s=this.j=!1;this.w="prev"==d||"prevunique"==d;this.unique="nextunique"==d||"prevunique"==d;this.L=d;this.qa=e;this.X=this.h=this.c=void 0};l.L="";l.V=null;l.unique=!1;l.w=!1;l.qa=!0;l.logger=null;function pd(a,b){a.U(b);qd(a);a.j=!0}l.O=function(a,b,c){null==a&&(this.j=!0);this.c=a;this.h=b;this.X=c;this.j?(this.K(),qd(this)):this.K(this.c)};
function qd(a){null!=a.h?a.h=lc(a.h):a.h=void 0;null!=a.c?a.c=lc(a.c):a.c=void 0;a.ea(a.s,a.c,a.h)}l.open=function(a,b,c,d){this.m=a;this.j=this.s=!1;this.c=c;this.h=d;this.openCursor(this.c,this.h)};function rd(a){a.s=!0;qd(a)}l.S=function(){return this.g?this.h:this.c};l.va=function(){return this.qa?this.S():this.X};l.ua=function(){};l.$=function(){};function sd(){};function td(a,b,c,d,e,f,g){this.b=a;this.f=b;this.m=g;this.v=!!this.f;this.c=r(f)?f:!!x(this.f);a="next";d&&e?a="prevunique":d?a="prev":e&&(a="nextunique");this.h=a;this.a=nc(c);this.g=ud;this.s=NaN}C(td,sd);td.prototype.c=!0;var ud="init";l=td.prototype;l.logger=null;l.clone=function(){var a=new td(this.b,this.f,this.a,vd(this),wd(this),this.c,this.m);a.s=this.s;return a};l.unique=function(a){return new td(this.b,this.f,this.a,vd(this),a,this.c,this.m)};
function xd(a,b,c){a=new td(a.b,a.f,a.a,vd(a),wd(a),a.c,a.m);a.i=b;a.j=c;a.g="rest";return a}function vd(a){return"prev"===a.h||"prevunique"===a.h}function wd(a){return"nextunique"===a.h||"prevunique"===a.h}l.load=function(a){a=a[0];a.Na(this.b,this.m||this.f,this.a,this.h,this.c);this.g="busy";var b=this;a.ea=function(a,d,e){b.i=d;b.j=e;b.g=a?"rest":"done"};a.openCursor(this.i,this.j);return a};function yd(a,b,c,d){b=b||ud;"busy"!=a.g&&(a.i=c,a.j=d,a.g=b)}l.stores=function(){return[this.b]};function zd(a){this.b=a||null;this.a=!1}zd.prototype.logger=null;function Ad(a,b){var c;a.a=vd(b[0]);for(c=0;c<b.length;c++);return!1}zd.prototype.c=function(){return[]};function Bd(a){Error.captureStackTrace?Error.captureStackTrace(this,Bd):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ConstraintError"}C(Bd,Error);Bd.prototype.name="ConstraintError";function Vb(a){Error.captureStackTrace?Error.captureStackTrace(this,Vb):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="InvalidStateError"}C(Vb,Error);
function Cd(a){Error.captureStackTrace?Error.captureStackTrace(this,Cd):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="InvalidAccessError"}C(Cd,Error);function Dd(a){Error.captureStackTrace?Error.captureStackTrace(this,Dd):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="NotFoundError"}C(Dd,Error);Dd.prototype.name="NotFoundError";
function Ed(a,b){Error.captureStackTrace?Error.captureStackTrace(this,Ed):this.stack=Error().stack||"";b&&(this.message=String(b));this.message+=" :"+a.message+" ["+a.code+"]";this.name="SQLError"}C(Ed,Error);function Fd(a,b){Error.captureStackTrace?Error.captureStackTrace(this,Fd):this.stack=Error().stack||"";b&&(this.message=String(b));this.message+=" :"+a.message;this.name="SecurityError"}C(Fd,Error);
function Gd(a){Error.captureStackTrace?Error.captureStackTrace(this,Gd):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.db.TimeoutError"}C(Gd,Error);function Hd(a,b){this.a=b}Hd.prototype.logger=null;function Id(a){this.f=a;this.a=null;this.b=0}Id.prototype.logger=null;Id.prototype.G=null;function Jd(a){return!!a.a&&!a.c}Id.prototype.F=null;function Kd(a,b,c,d,e,f){this.j=a;this.K=b;this.a=this.f=0;this.H=d;this.B=e;this.h=c||Ld;this.m=f||0}Kd.prototype.logger=null;Kd.prototype.type=function(){return this.j.Ma()};Kd.prototype.P=function(){return"B"+this.K+"T"+this.f};var Ld="single";function Md(a){if(a)if(ca(a.abort))a.abort();else if(ca(a.executeSql))a.executeSql("ABORT",[],null,function(){return!0});else throw new Ab;else throw new Vb("No active transaction");};function Nd(a,b,c,d,e,f){Kd.call(this,a,b,c,d,e,f);this.c=[];this.g=[];this.i=null;this.b=new Id(b);this.s=f||0;this.v=!1}C(Nd,Kd);l=Nd.prototype;l.logger=null;
function Od(a,b,c){if("multi"==a.h)a:if(a=a.b,!a.G||!a.mode||c!=a.mode&&(a.mode!=F||c!=Gb)||b.length>a.G.length)b=!1;else{for(c=0;c<b.length;c++)if(-1==a.G.indexOf(b[c])){b=!1;break a}b=!0}else if("repeat"==a.h)a:if(a=a.b,a.G&&a.mode&&c==a.mode&&a.G.length==b.length){for(c=0;c<b.length;c++)if(-1==a.G.indexOf(b[c])){b=!1;break a}b=!0}else b=!1;else b="all"==a.h?!0:!1;return b}function Pd(a){var b=0<a.c.length?a.c[0].G:null,c=0<a.c.length?a.c[0].mode:null;return null!=b&&null!=c?Od(a,b,c):!1}
l.abort=function(){Md(this.i)};
l.T=function(a,b,c,d){var e=x(b)?[b]:b,f=r(c)?c:Gb,g=this;if(this.b.a||!nd(this.j)&&this.v)this.c.push({na:a,G:b,mode:f,F:d});else{d&&this.g.push(d);if(this.s&&this.f>=this.s)throw new Bb("Exceed maximum number of transactions of "+this.s);this.v=!0;this.j.transaction(function(c){var d=g.b;d.a=c;d.c=!1;d.G=b;d.mode=f;d.b++;d.F=null;P(b);a(g);for(a=null;Pd(g);)c=g.c.shift(),c.F&&g.g.push(c.F),c.na()},e,f,function(a,b){var c=g.b;c.a&&(c.a=null,c.G=null,c.mode=null,ca(c.F)&&c.F(a,b),c.F=null);for(c=
0;c<g.g.length;c++)(0,g.g[c])(a,b);g.g.length=0;(c=g.c.shift())&&g.T(c.na,c.G,c.mode,c.F);g.a=0})}};l.P=function(){var a=this.b;return"B"+a.f+"T"+a.b};l.request=function(a,b,c,d){function e(a,b){f.a=null;d&&d(a,b)}var f=new H(a);a=c||Gb;var g=this;Jd(this.b)&&Od(this,b,a)?(b=this.b.a,this.a++,Tb(f,b,this.P()+"R"+this.a),this.g.push(e)):g.T(function(){var a=g.b.a;g.a++;Tb(f,a,g.P()+"R"+g.a)},b,a,e);return f};
l.ca=function(a,b,c,d,e){d=d||Gb;var f=this,g;if(Jd(f.b)&&Od(this,c,d)){var h=f.b.a;f.a++;g=f.P()+"R"+f.a;b(h,g,function(b,c){f.i=h;c?a.l(b):a.callback(b);f.i=null});b=null}else f.T(function(){var c=f.b.a;f.a++;g=f.P()+"R"+f.a;b(c,g,function(b,d){f.i=c;d?a.l(b):a.callback(b);f.i=null});b=null},c,d,e)};l.getName=function(){return this.j.getName()};function Qd(a,b){Nd.call(this,a,b)}C(Qd,Nd);Qd.prototype.logger=null;Qd.prototype.request=function(a,b,c){var d,e,f,g=Qd.D.request.call(this,a,b,c,function(a,b){g.a=null;if(d)"complete"!=a&&(f=!0,e=b),d(e,f);else{var c=new Gd;I(g,c,!0)}});Wb(g,function(a,b,c){f=b;e=a;d=c});return g};
Qd.prototype.ca=function(a,b,c,d,e){var f,g,h=new D;ob(h,function(a){g=!1;f=a},function(a){g=!0;f=a});Qd.D.ca.call(this,h,b,c,d,function(b,c){if("complete"!=b)a.l(c);else if(!0===g)a.l(f);else if(!1===g)a.callback(f);else{var d=new Gd;a.l(d)}e&&(e(b,c),e=void 0)})};function Rd(a,b,c){this.c=a;this.b=b;this.a=c;this.f=null}Rd.prototype.logger=null;Rd.prototype.g=function(){return this.a.f};Rd.prototype.abort=function(){this.a.abort()};function W(a){if(!a.f){var b;b=a.c;var c=b.Ma();if("indexeddb"==c)b=new Sd(0,b.c);else if("websql"==c||"sqlite"==c)b=new Td(0,b.c);else throw new Cb("No executor for "+c);a.f=b}return a.f}
function Ud(a,b){var c=x(b)?b:B(b)?b.name:void 0;if(!x(c))throw new E("store name "+c+" must be a string, but "+typeof c);var d=U(a.b,c);if(!d){if(!a.b.a())throw new E('store name "'+c+'" not found.');d=Gc(B(b)?b:{name:c});var e=a.c,f=d,g=f instanceof Fc?f:Gc(f),f=U(e.c,f.name);if(0==Tc(g,f).length)(new D).callback(!1);else if(e.c instanceof dd)ed(e.c,g),e.a?(e.a.close(),e.a=null,kd(e)):(new D).callback(!1);else throw new gd("");}else if(a.b.a()&&B(b)&&(e=Gc(b),e=Tc(d,e)))throw new Ab(e);if(!d)throw new Dd(c);
return d};function X(a,b,c){Rd.call(this,a,b,c)}C(X,Rd);l=X.prototype;l.logger=null;
l.count=function(a,b,c,d){var e,f,g,h;if(null!=a)if(t(a)){if(r(c)||r(b))throw new E("too many arguments.");f=a;for(var k=0;k<f.length;k++)if(!bd(this.b,f[k]))throw new E('store name "'+f[k]+'" at '+k+" not found.");zb("countStores: "+P(f));e=this.a.request("d",f);J(e,function(){W(this).Aa(e,f)},this)}else if(x(a)){k=U(this.b,a);if(!k)throw new E('store name "'+a+'" not found.');f=[a];if(x(b))g=b,B(c)?h=nc(c):h=null;else if(B(b)||null==b)if(B(b))h=nc(b);else{if(null!=b)throw new E("key range must be  an object but found "+
Wc(b)+" of type "+typeof b);h=null}else throw new E('invalid second argument for count "'+Wc(c)+'" of type '+typeof b);zb("countKeyRange: "+a+" "+(g?g:"")+P(h));e=this.a.request("d",f);S(k,e,arguments);J(e,function(){W(this).Ua(e,f[0],h,g,!!d)},this)}else throw new E("Invalid store name or store names.");else k=ad(this.b),e=this.a.request("d",k),Wb(e,function(a,b,c){if(b)c(a,!0);else{for(var d=b=0;d<a.length;d++)b+=a[d];c(b,!1)}},this),J(e,function(){W(this).Aa(e,f)},this);return e};
l.get=function(a,b){var c=this,d;if(a instanceof jc){var e=a,f=e.b,g=U(this.b,f);if(!g){if(this.b.a()){if(nd(this.c))return Yb("e",void 0);d=new H("e");this.c.sa(function(){ob(c.get(a,b),function(a){d.callback(a)},function(a){d.l(a)})});return d}throw new E("Store: "+f+" not found.");}var h=e.a;d=this.a.request("ek",[f]);S(g,d,arguments,void 0,this);J(d,function(){W(this).Ea(d,f,h)},this)}else if(x(a)&&r(b)){var k=a,g=U(this.b,k);if(!g){if(this.b.a()){if(nd(this.c))return Yb("e",void 0);d=new H("e");
this.c.sa(function(){ob(c.get(a,b),function(a){d.callback(a)},function(a){d.l(a)})});return d}throw new E('Store name "'+k+'" not found.');}var m=b;d=this.a.request("e",[k]);S(g,d,arguments,void 0,this);J(d,function(){W(this).Ea(d,k,m)},this)}else throw new E("get require valid input arguments.");return d};
l.ub=function(a,b,c,d,e){var f=U(this.b,a),g,h,k,m=null;B(b)&&(m=nc(b));if(r(c))if(z(c))g=c;else throw new E("limit must be a number, but "+c+" is "+typeof c);else g=100;if(r(d))if(z(d))h=d;else throw new E("offset must be a number, but "+d+" is "+typeof d);else h=0;if(r(e))if(ba(e))k=e;else throw new E("reverse must be a boolean, but "+e+" is "+typeof e);var p=this.a.request("g",[a]);S(f,p,arguments);J(p,function(){W(this).ba(p,2,a,null,m,g,h,k,!1)},this);return p};
l.ga=function(a,b,c,d,e,f,g){var h,k,m,p,n,u=U(this.b,a);h=nc(c);if(z(d))k=d;else{if(r(d))throw new E("limit must be a number");k=100}if(z(e))m=e;else{if(r(e))throw new E("offset must be a number");m=0}if(r(f))if(ba(f))p=f;else throw new E("reverse must be a boolean");if(r(g))if(ba(g))n=g;else throw new E("unique must be a boolean");var v=this.a.request("i",[a]);S(u,v,arguments);J(v,function(){W(this).ba(v,2,a,b,h,k,m,p,n)},this);return v};
l.aa=function(a,b,c,d,e,f,g){var h=U(this.b,a);return this.b.a()&&!h?Yb("g",[]):x(b)?this.ga(a,b,c,d,e,f,g):this.ub(a,b,c,d,e)};
l.values=function(a,b,c,d,e,f,g){var h=this,k;if(x(a)){var m=a,p=U(this.b,m);if(!p){if(this.b.a()){if(nd(this.c))return Yb("s",[]);k=new H("s");this.c.sa(function(){ob(h.values(a,b,c,d,e,f),function(a){k.callback(a)},function(a){k.l(a)})});return k}throw new Dd(m);}if(t(b)){var n=b;k=this.a.request("v",[m]);S(p,k,arguments,void 0,this);J(k,function(){W(this).Wa(k,m,n)},this)}else k=x(b)?this.ja(m,b,c,d,e,f,g):this.yb(m,b,c,d,e)}else if(t(a))if(a[0]instanceof jc){for(var p=[],u=a,v=0;v<u.length;v++){var y=
u[v].b;if(!bd(this.b,y)){if(this.b.a())return p=[],p[u.length-1]=void 0,Yb("e",p);throw new E("Store: "+y+" not found.");}0<=ua(p,y)||p.push(y)}zb("listByKeys: "+P(p)+" "+u.length+" keys");k=this.a.request("w",p);J(k,function(){W(this).Xa(k,u)},this)}else throw new E("first argumentmust be array of ydn.db.Key, but "+a[0]+" of "+typeof a[0]+" found.");else throw new E("first argument "+a+" is invalid.");return k};
l.yb=function(a,b,c,d,e){var f=U(this.b,a),g,h,k,m=null;B(b)&&(m=nc(b));if(r(c))if(z(c))g=c;else throw new E("limit must be a number, but "+c+" is "+typeof c);else g=100;if(r(d))if(z(d))h=d;else throw new E("offset must be a number, but "+d+" is "+typeof d);else h=0;if(r(e))if(ba(e))k=e;else throw new E("reverse must be a boolean, but "+e+" is "+typeof e);var p=this.a.request("s",[a]);S(f,p,arguments);J(p,function(){W(this).ba(p,4,a,null,m,g,h,k,!1)},this);return p};
l.ja=function(a,b,c,d,e,f,g){var h=U(this.b,a),k,m,p,n,u=nc(c);if(r(d))if(z(d))k=d;else throw new E("limit must be a number.");else k=100;if(r(e))if(z(e))m=e;else throw new E("offset must be a number.");else m=0;if(ba(f))p=f;else if(r(f))throw new E("reverse must be a boolean, but "+f);if(r(g))if(ba(g))n=g;else throw new E("unique must be a boolean");var v=this.a.request("u",[a]);S(h,v,arguments);J(v,function(){W(this).ba(v,4,a,b,u,k,m,p,n)},this);return v};
l.add=function(a,b,c){if(t(b))return this.ka(a,b,c);a=Ud(this,a);var d=a.getName(),e;if(x(a.keyPath)&&r(c))throw new E("key must not be provided while the store uses in-line key.");if(!a.keyPath&&!a.b&&!r(c))throw new E("out-of-line key must be provided for store: "+d);if(t(b)){for(var f=0;f<b.length;f++)Uc(a,b[f]);e=this.a.request("b",[d],F);J(e,function(){W(this).N(e,!1,!1,d,b,c)},this);a.M&&e.A(function(){},this)}else if(B(b))Qc(a,b,c),Uc(a,b),e=this.a.request("a",[d],F),J(e,function(){W(this).N(e,
!1,!0,d,[b],[c])},this),a.M&&e.A(function(){},this);else throw new E("record must be an object or array list of objects, but "+b+" of type "+typeof b+" found.");return e};
l.ka=function(a,b,c){a=Ud(this,a);var d=a.getName(),e;if(x(a.keyPath)&&r(c))throw new E("key must not be provided while the store uses in-line key.");if(!a.keyPath&&!a.b&&!r(c))throw new E("out-of-line key must be provided for store: "+d);if(t(b)){for(var f=0;f<b.length;f++)Uc(a,b[f]);e=this.a.request("b",[d],F);J(e,function(){W(this).N(e,!1,!1,d,b,c)},this);a.M&&e.A(function(){},this)}else throw new E("record must be an array list of objects, but "+b+" of type "+typeof b+" found.");return e};
l.put=function(a,b,c){var d,e=this;if(a instanceof jc){var f=a,g=f.b,h=U(this.b,g);if(!h)throw new E('store "'+g+'" not found.');if(h.keyPath){var k=Qc(h,b);if(null!=k){if(0!=K(k,f.a))throw new E("Inline key must be "+f+" but "+k+" found.");}else Rc(h,b,f.a);return this.put(g,b)}return this.put(g,b,f.a)}if(t(a)){for(var m=a,p=b,f=[],g=0,h=m.length;g<h;g++){k=m[g].b;-1==ua(f,k)&&f.push(k);var n=U(this.b,k);if(!n)throw new E('store "'+k+'" not found.');n.keyPath&&Rc(n,p[g],m[g].a)}zb("putByKeys: to "+
P(f)+" "+p.length+" objects");for(g=0;g<p.length;g++)Uc(n,p[g]);d=this.a.request("l",f,F);S(n,d,arguments);J(d,function(){W(e).bb(d,p,m)},this)}else if(x(a)||B(a)){var n=Ud(this,a),u=n.getName();if(n.keyPath&&r(c))throw new E("key must not be provided while the store uses in-line key.");if(!n.keyPath&&!n.b&&!r(c))throw new E("out-of-line key must be provided for store: "+u);if(t(b)){for(var v=b,y=c,g=0;g<v.length;g++)Uc(n,v[g]);d=this.a.request("k",[u],F);S(n,d,arguments);J(d,function(){W(this).N(d,
!0,!1,u,v,y)},this);n.M&&d.A(function(){},this)}else if(B(b)){var A=b,Q=c;if(r(q.Blob)&&A instanceof Blob&&n.W&&!n.keyPath&&0==n.a.length&&xb)d=new H("j"),f=new FileReader,f.onload=function(a){var b=a.target.result,c=e.a.request("j",[u],F);S(n,c,[u,A,Q]);J(c,function(){W(e).N(c,!0,!0,u,[b],[Q])},this);ob(c,function(a){d.callback(a)},function(a){d.l(a)})},f.onerror=function(a){d.l(a)},f.onabort=function(a){d.l(a)},f.readAsDataURL(A);else{Uc(n,A);d=this.a.request("j",[u],F);var R=[u,A,Q];S(n,d,R);J(d,
function(){var a=r(Q)?[R[2]]:void 0;W(e).N(d,!0,!0,u,[R[1]],a)},this)}n.M&&d.A(function(){},this)}else throw new E("put record value must be Object or array of Objects");}else throw new E("the first argument of put must be store name, store schema or array of keys.");return d};
l.ta=function(a,b,c){var d,e=Ud(this,a),f=e.getName();if(e.keyPath&&r(c))throw new E("key must not be provided while the store uses in-line key.");if(!e.keyPath&&!e.b&&!r(c))throw new E("out-of-line key must be provided for store: "+f);for(var g=b,h=c,k=0;k<g.length;k++)Uc(e,g[k]);d=this.a.request("k",[f],F);S(e,d,arguments);J(d,function(){W(this).N(d,!0,!1,f,g,h)},this);e.M&&d.A(function(){},this);return d};
l.clear=function(a,b){var c;if(x(a)){var d=U(this.b,a);if(!d)throw new E('store name "'+a+'" not found.');if(B(b)){var e=nc(b);if(null===e)throw new E("clear method requires a valid non-null KeyRange object.");zb("clearByKeyRange: "+a+":"+P(e));c=this.a.request("c",[a],F);S(d,c,[a,e]);J(c,function(){W(this).Sa(c,a,e)},this)}else{if(r(b))throw new E("clear method requires a valid KeyRange object as second argument, but found "+b+" of type "+typeof b);c=this.a.request("c",[a],F);J(c,function(){W(this).ya(c,
[a])},this)}}else if(!r(a)||t(a)&&x(a[0])){var f=a||ad(this.b);zb("clearByStores: "+P(f));c=this.a.request("c",f,F);J(c,function(){W(this).ya(c,f)},this)}else throw new E('first argument "'+a+'" is invalid.');return c};
l.wa=function(a,b,c){var d;if(x(a)){var e=U(this.b,a);if(!e)throw new E('store name "'+a+'" not found.');if(r(c))if(x(b)){var f=Jc(e,b);if(!f)throw new E("index: "+b+" not found in "+a);if(B(c)||null===c){var g=nc(c);d=this.a.request("p",[a],F);J(d,function(){W(this).cb(d,a,f.getName(),g)},this)}else throw new E("key range "+c+' is invalid type "'+typeof c+'".');}else throw new E('index name "'+b+'" must be a string, but '+typeof b+" found.");else if(x(b)||z(b)||w(b)||b instanceof Date){d=this.a.request("m",
[a],F);var h=[a,b];S(e,d,h);J(d,function(){W(this).Ia(d,a,h[1])},this);e.M&&d.A(function(){},this)}else if(B(b))g=nc(b),zb("removeByKeyRange: "+a+":"+P(g)),d=this.a.request("n",[a],F),S(e,d,[a,g]),J(d,function(){W(this).eb(d,a,g)},this),e.M&&d.A(function(){},this);else throw new E('Invalid key or key range "'+b+'" of type '+typeof b);}else if(a instanceof jc){var k=a.b,e=U(this.b,k);d=this.a.request("m",[k],F);var m=[k,a.a];S(e,d,m);J(d,function(){W(this).Ia(d,k,m[1])},this)}else if(t(a)){b=[];c=
0;for(e=a.length;c<e;c++){var p=a[c].b;-1==ua(b,p)&&b.push(p)}if(1>b.length)throw new E('at least one valid key required in key list "'+Wc(a)+'"');d=this.a.request("o",b,F);J(d,function(){W(this).fb(d,a)},this)}else throw new E('first argument requires store name, key (ydn.db.Key) or list of keys (array) , but "'+Wc(a)+'" ('+aa(a)+") found.");return d};function Vd(a,b,c){Rd.call(this,a,b,c)}C(Vd,X);l=Vd.prototype;l.logger=null;l.get=function(a,b){if(a instanceof td){var c=a.b,d=U(this.b,c);if(!d)throw new E('store "'+c+'" not found.');var e=a.f;if(r(e)&&!Nc(d,e))throw new E('index "'+e+'" not found in store "'+c+'".');var f=this.a.request("f",[c]);J(f,function(){Wd(this,5,f,a,1)},this);return f}return Vd.D.get.call(this,a,b)};
l.Ha=function(a,b){var c=100;if(z(b)){if(c=b,1>c)throw new E("limit must be a positive value, but "+b);}else if(r(b))throw new E("limit must be a number,  but "+b);var d=this.a.request("h",[a.b]);J(d,function(){a.v?Wd(this,1,d,a,c):Wd(this,2,d,a,c)},this);return d};l.aa=function(a,b,c,d,e,f,g){return a instanceof td?this.Ha(a,b):Vd.D.aa.call(this,a,b,c,d,e,f,g)};l.za=function(a){var b=this.a.request("d",[a.b]);J(b,function(){Wd(this,6,b,a)},this);return b};
l.count=function(a,b,c,d){if(a instanceof td){if(r(b)||r(c))throw new E("too many arguments.");return this.za(a)}return Vd.D.count.call(this,a,b,c,d)};l.Ja=function(a,b){var c;if(z(b)){if(c=b,1>c)throw new E("limit must be a positive value, but "+c);}else if(r(b))throw new E("limit must be a number, but "+b);var d=this.a.request("t",[a.b]);J(d,function(){a.c?Wd(this,2,d,a,c):Wd(this,4,d,a,c)},this);return d};
l.values=function(a,b,c,d,e,f){return a instanceof td?this.Ja(a,b):Vd.D.values.call(this,a,b,c,d,e,f)};
function Xd(a,b,c){var d,e=F||Gb,f=[];for(d=0;d<c.length;d++)for(var g=c[d].stores(),h=0;h<g.length;h++)0<=ua(f,g[h])||f.push(g[h]);d=a.a.request("qa",f);a.a.ca(d,function(d,e,f){function g(){for(var b=0,f=0;f<c.length;f++){var n=c[f],p=[W(a).b(d,e,n.b)],n=n.load(p);n.U=h;n.K=ia(v,b);O[f]=n;Q[b]=f;b++}A=c.length}function h(a){for(var b=0;b<O.length;b++)rd(O[b]);za(O);f(a,!0)}function v(a,d){if(y)throw new fd;T++;var e=T===A,g=Q[a],h=c[g],k=O[g],g=k.S(),k=k.va();R[a]=d;N[a]=h.v?h.c?g:k:h.c?d:k;if(e){var m;
b instanceof zd?m=b.c(R,N):m=b(R,N);e=[];h=[];g=[];k=[];if(t(m))for(var n=0;n<m.length;n++)!0===m[n]?g[n]=1:!1===m[n]?k[n]=!0:h[n]=m[n];else if(null===m)e=[];else if(r(m))if(B(m))e=m.continuePrimary||[],h=m["continue"]||[],g=m.advance||[],k=m.restart||[];else throw new Bb("scan callback output");else for(e=[],n=0;n<c.length;n++)r(Q[n])&&(g[n]=1);for(n=T=m=0;n<c.length;n++)null!=e[n]||r(h[n])||null!=k[n]||null!=g[n]||T++;for(n=0;n<c.length;n++)if(null!=e[n]||r(h[n])||null!=k[n]||null!=g[n]){var u=
Q[n];if(!r(u))throw new hd(n+" is not an iterator.");var u=c[u],v=O[n];R[n]=void 0;N[n]=void 0;if(null!=k[n])u=v,u.j=!1,u.s=!1,u.openCursor(void 0,void 0);else if(r(h[n]))v.$(h[n]);else if(null!=e[n])v.ua(e[n]);else if(null!=g[n])v.advance(1);else throw new fd(u+": has no action");m++}if(0==m){for(m=0;m<O.length;m++)rd(O[m]);y=!0;za(O);f(void 0)}}}var y=!1,A,Q=[],R=[],N=[],O=[],T=0;b instanceof zd?Ad(b,c)||g():g()},f,e);return d}
l.open=function(a,b,c,d){c=c||Gb;var e=this,f=this.a.request("i5",b.stores(),c);J(f,function(c){for(var h=Xb(f),k=b.stores(),m=[],p=0;p<k.length;p++)m[p]=W(e).b(c,h,k[p]);var n=b.load(m);n.U=function(a){I(f,a,!0)};n.K=function(b){if(null!=b){var c=a.call(d,n);!0===c?(n.j=!1,n.s=!1,n.openCursor(void 0,void 0)):B(c)?!0===c.restart?(b=c["continue"],c=c.continuePrimary,n.j=!1,n.s=!1,n.openCursor(c,b)):null!=c["continue"]?n.$(c["continue"]):null!=c.continuePrimary?n.ua(c.continuePrimary):(rd(n),I(f,void 0)):
null===c?(rd(n),I(f,void 0)):null!=c?n.$(c):n.advance(1)}else rd(n),I(f,void 0)}},this);return f};function Yd(a,b,c,d){var e=c.b,f=c.f||null,g=d||100,h=a.a.request("u",[e]),k="done"==c.g||c.g==ud?[]:[c.i,c.j];J(h,function(){W(this).ba(h,b,e,f,c.a?c.a instanceof tc?c.a:tc.bound(c.a.lower,c.a.upper,c.a.lowerOpen,c.a.upperOpen):null,g,0,vd(c),wd(c),k)},a);h.A(function(){null!=k[0]?yd(c,"rest",k[0],k[1]):yd(c)});return h}
function Wd(a,b,c,d,e){var f=[],g=c.a,h=Xb(c);a=W(a);for(var k=[],m=d.stores(),p=0;p<m.length;p++)k[p]=a.b(g,h,m[p]);var n=d.load(k);n.U=function(a){rd(n);I(c,a,!0)};var u=0,v=!1;n.K=function(a){v||(v=!0);null!=a?(n.S(),u++,1==b?f.push(a):2==b?f.push(n.S()):3==b?f.push([a,n.S()]):6!=b&&f.push(n.va()),5==b?(rd(n),I(c,f[0])):6==b||!r(e)||u<e?n.$():(rd(n),I(c,f))):(rd(n),I(c,5==b?f[0]:6==b?u:f))}};function Zd(a,b,c,d){this.f=a;this.a=Aa(c);this.b=d;this.c=[]}Zd.prototype.f=null;function $d(a,b,c){if(a.f)c&&a.c.push(c),b(a.f);else throw new Cb("tx committed on ParallelTxExecutor");};function ae(a,b,c,d,e,f){Kd.call(this,a,b,c,d,e,f);this.c=this.b=null}C(ae,Kd);l=ae.prototype;l.logger=null;l.abort=function(){Md(this.c)};
l.mb=function(a,b){var c;if("multi"==this.h)a:if(c=this.b,!c.a||!c.b||b!=c.b&&(c.b!=F||b!=Gb)||a.length>c.a.length)c=!1;else{for(var d=0;d<a.length;d++)if(-1==c.a.indexOf(a[d])){c=!1;break a}c=!0}else if("repeat"==this.h)a:if(c=this.b,c.a&&c.b&&b==c.b&&c.a.length==a.length){for(d=0;d<a.length;d++)if(-1==c.a.indexOf(a[d])){c=!1;break a}c=!0}else c=!1;else c="all"==this.h?!0:!1;return c};
l.T=function(a,b,c,d){function e(c){h.f++;k=new Zd(c,0,b,g);P(b);h.b=k;$d(h.b,a,d)}function f(a,b){if(k){for(var c=k,d=0;d<c.c.length;d++)c.c[d](a,b);c.c.length=0;c.f=null;c.a=null;c.c=null}h.a=0}this.H&&(b=this.H);this.B&&(c=this.B);var g=r(c)?c:Gb,h=this,k;if(this.b&&this.b.f&&this.mb(b,g))$d(this.b,a,d);else{if(this.m&&this.f>=this.m)throw new Bb("Exceed maximum number of transactions of "+this.m);this.j.transaction(e,b,g,f)}};
l.request=function(a,b,c,d){var e=new H(a),f=this;this.T(function(a){f.a++;Tb(e,a,f.P()+"R"+f.a)},b,c||Gb,function(a,b){e.a=null;d&&d(a,b)});return e};l.ca=function(a,b,c,d,e){var f=this,g;this.T(function(c){f.a++;g=f.P()+"R"+f.a;b(c,g,function(b,d){f.c=c;g=f.P()+"R"+f.a;d?a.l(b):a.callback(b);f.c=null});b=null},c,d,e)};function be(a,b){ae.call(this,a,b,Ld)}C(be,ae);be.prototype.logger=null;be.prototype.mb=function(){return!1};be.prototype.request=function(a,b,c){var d,e,f,g=be.D.request.call(this,a,b,c,function(a,b){g.a=null;if(d)"complete"!=a&&(f=!0,e=b),d(e,f);else{var c=new Gd;I(g,c,!0)}});Wb(g,function(a,b,c){f=b;e=a;d=c});return g};
be.prototype.ca=function(a,b,c,d,e){var f,g,h=new D;ob(h,function(a){g=!1;f=a},function(a){g=!0;f=a});be.D.ca.call(this,h,b,c,d,function(b,c){if("complete"!=b)a.l(c);else if(!0===g)a.l(f);else if(!1===g)a.callback(f);else{var d=new Gd;a.l(d)}e&&(e(b,c),e=void 0)})};function ce(a,b,c){V.call(this,a,b,c);this.Y=0;a=!0;b=Ld;c&&(r(c.isSerial)&&(a=!!c.isSerial),c.policy&&(b=c.policy));c=de(this,b,a);this.i=de(this,"atomic",!1);this.b=this.ha(c,this.i)}C(ce,V);l=ce.prototype;l.Y=0;l.nb=function(a,b,c,d,e,f){a=a||Ld;var g;"readonly"==d?g=Gb:"readwrite"==d&&(g=F);a=de(this,a,b,c,g,e);return this.ha(a,f?null:this.i)};l.ha=function(a){return new Rd(this,this.c,a)};
function de(a,b,c,d,e,f){if(c){if("multi"==b||"repeat"==b||"all"==b||b==Ld)return new Nd(a,a.Y++,b,d,e,f);if("atomic"==b)return new Qd(a,a.Y++);throw new E('Invalid requestType "'+b+'"');}if("multi"==b||"repeat"==b||"all"==b||b==Ld)return new ae(a,a.Y++,b,d,e,f);if("atomic"==b)return new be(a,a.Y++);throw new E('Invalid requestType "'+b+'"');}
l.wb=function(a,b,c){this.Y++;b=b||ad(this.c);var d=Gb;if(c)if("readwrite"==c)d=F;else if("readonly"!=c)throw new E('Invalid transaction mode "'+c+'"');var e=de(this,"all",!1,b,d,1),f=this.ha(e,this.i),g=new H("q");e.T(function(b){Tb(g,b,e.P()+"R0");a(f)},b,d,function(a){g.a=null;I(g,e.f,"complete"!==a)});return g};l.Hb=function(){return this.b?this.b.a.f:NaN};function Y(a,b,c){ce.call(this,a,b,c);a=this.c;for(b=0;b<a.c.length;b++){c=a.c[b];var d=U(a,c.getName());if(d){if(!Nc(d,"k"))throw new E('full text index store "'+d.getName()+'" must have "keyword" index');if(!Nc(d,"v"))throw new E('full text index store "'+d.getName()+'" must have "keyword" index');if("id"!=d.keyPath)throw new E('full text index store "'+d.getName()+'" must use "id" as key path.');}else throw new E('full text index store "'+c.getName()+'" required.');for(d=0;d<c.count();d++){var e=
c.index(d);if(!U(a,e.a))throw new E('full text source store "'+e.a+'" does not exist for full text index "'+c.getName()+'"');}}}C(Y,ce);l=Y.prototype;l.ha=function(a){return new X(this,this.c,a)};l.add=function(a,b,c){return this.b.add(a,b,c)};l.ka=function(a,b,c){return this.b.ka(a,b,c)};l.count=function(a,b,c,d){return this.b.count(a,b,c,d)};l.get=function(a,b){return this.b.get(a,b)};l.aa=function(a,b,c,d,e,f,g){return this.b.aa(a,b,c,d,e,f,g)};
l.ga=function(a,b,c,d,e,f,g){return this.b.ga(a,b,c,d,e,f,g)};l.values=function(a,b,c,d,e,f){return this.b.values(a,b,c,d,e,f)};l.ja=function(a,b,c,d,e,f){return this.b.ja(a,b,c,d,e,f)};l.put=function(a,b,c){return this.b.put(a,b,c)};l.ta=function(a,b,c){return this.b.ta(a,b,c)};l.clear=function(a,b,c){return this.b.clear(a,b,c)};l.wa=function(a,b,c){return this.b.wa(a,b,c)};function ee(a,b,c){Y.call(this,a,b,c)}C(ee,Y);l=ee.prototype;l.ha=function(a){return new Vd(this,this.c,a)};l.open=function(a,b,c,d){return this.b.open(a,b,c,d)};l.za=function(a){return this.b.za(a)};l.Ja=function(a,b){return this.b.Ja(a,b)};l.Ha=function(a,b){return this.b.Ha(a,b)};function fe(a,b,c,d){od.call(this,a,0,c,d);this.b=null}C(fe,od);l=fe.prototype;l.logger=null;l.ma=function(a){(a=a.target.result)?this.O(a.key,a.primaryKey,a.value):this.O()};
l.openCursor=function(a,b){function c(a,b,c){n.b=p;n.b.onsuccess=ha(n.ma,n);n.O(a,n.g?b:void 0,c);p=null}var d=this.V,e=this.m.objectStore(this.pb),f=x(this.i)?e.index(this.i):null;if(r(a))var g=f?!r(b):!0,h=d?d.lower:void 0,k=d?d.upper:void 0,m=d?!!d.lowerOpen:!1,d=d?!!d.upperOpen:!1,d=mc(this.w?new L(h,a,m,g):new L(a,k,g,d));var p;this.qa?f?p=null!=this.L?f.openKeyCursor(d,this.L):null!=d?f.openKeyCursor(d):f.openKeyCursor():p=null!=this.L?e.openCursor(d,this.L):null!=d?e.openCursor(d):e.openCursor():
f?p=null!=this.L?f.openCursor(d,this.L):null!=d?f.openCursor(d):f.openCursor():p=null!=this.L?e.openCursor(d,this.L):null!=d?e.openCursor(d):e.openCursor();var n=this;p.onerror=function(a){var b=p.error;a.preventDefault();pd(n,b)};null!=a?p.onsuccess=function(d){if(d=d.target.result){var e=G.cmp(d.key,a),f=n.w?-1:1;if(e==f)c(d.key,d.primaryKey,d.value);else if(e==-f)d["continue"](a);else if(null!=b)if(G.cmp(d.primaryKey,b)==f)c(d.key,d.primaryKey,d.value);else d["continue"]();else d["continue"]()}else c()}:
(n.b=p,n.b.onsuccess=ha(n.ma,n))};l.Ga=function(){return!!this.b};l.update=function(a){var b=this.b.result;if(b){var c=new D;a=b.update(a);a.onsuccess=function(a){c.callback(a.target.result)};a.onerror=function(a){a.preventDefault();c.l(a)};return c}throw new Cd("cursor gone");};l.clear=function(){var a=this.b.result;if(a){var b=new D,a=a["delete"]();a.onsuccess=function(){b.callback(1)};a.onerror=function(a){a.preventDefault();b.l(a)};return b}throw new Cd("cursor gone");};
l.advance=function(a){var b=this.b.result;if(1==a)b["continue"]();else b.advance(a)};l.ua=function(a){var b,c=this.b.result,d=this;this.b.onsuccess=function(e){if(c=e.target.result)if(b=G.cmp(c.primaryKey,a),0==b||1==b&&!d.w||-1==b&&d.w)d.b.onsuccess=ha(d.ma,d),d.O(c.key,d.g?c.primaryKey:void 0,c.value);else c["continue"]();else d.b.onsuccess=ha(d.ma,d),d.O()};c["continue"]()};l.$=function(a){var b=this.b.result;if(null!=a)b["continue"](a);else b["continue"]()};function ge(a,b){this.a=b}C(ge,Hd);l=ge.prototype;l.logger=null;l.Aa=function(a,b){function c(e){var f=a.a.objectStore(b[e]).count();f.onsuccess=function(f){d[e]=f.target.result;e++;e==b.length?I(a,d):c(e)};f.onerror=function(b){b.preventDefault();I(a,f.error,!0)}}var d=[];0==b.length?I(a,[]):c(0)};
l.N=function(a,b,c,d,e,f){function g(d){if(null==e[d])if(k++,k==e.length)I(a,h,m);else{var u=d+10;u<e.length&&g(u)}var v,u=e[d];v=f&&null!=f[d]?b?p.put(u,f[d]):p.add(u,f[d]):b?p.put(u):p.add(u);v.onsuccess=function(b){k++;h[d]=b.target.result;k==e.length?I(a,c?h[0]:h,m):(b=d+10,b<e.length&&g(b))};v.onerror=function(b){k++;var f=v.error;Wc(e[d]);h[d]=f;m=!0;b.preventDefault();k==e.length?I(a,c?h[0]:h,m):(b=d+10,b<e.length&&g(b))}}var h=[],k=0,m=!1,p=a.a.objectStore(d);if(0<e.length)for(d=0;10>d&&d<
e.length;d++)g(d);else I(a,[])};l.bb=function(a,b,c){function d(h){var m=c[h],p=a.a.objectStore(m.b),n;n=null===p.keyPath?p.put(b[h],m.a):p.put(b[h]);n.onsuccess=function(c){f++;e[h]=c.target.result;f==b.length?I(a,e,g):(c=h+10,c<b.length&&d(c))};n.onerror=function(c){f++;e[h]=n.error;g=!0;c.preventDefault();f==b.length?I(a,e,g):(c=h+10,c<b.length&&d(c))}}var e=[],f=0,g=!1;if(0<b.length)for(var h=0;10>h&&h<b.length;h++)d(h);else I(a,e,g)};
l.Ia=function(a,b,c){var d=a.a.objectStore(b).openCursor(tc.only(c));d.onsuccess=function(b){if(b=b.target.result){var c=b["delete"]();c.onsuccess=function(){I(a,1)};c.onerror=function(){I(a,c.error,!0)}}else I(a,0)};d.onerror=function(b){b.preventDefault();I(a,d.error,!0)}};
l.fb=function(a,b){function c(h){h++;if(h>=b.length)0<g.length?I(a,g,!0):I(a,d);else{b[h].b!=e&&(e=b[h].b,f=a.a.objectStore(e));var k=f["delete"](b[h].a);k.onsuccess=function(){d++;c(h)};k.onerror=function(a){a.preventDefault();g[h]=k.error;c(h)}}}var d=0,e,f,g=[];c(-1)};
l.eb=function(a,b,c){var d=a.a.objectStore(b),e=d.count(c);e.onsuccess=function(b){var e=b.target.result,h=d["delete"](c);h.onsuccess=function(){I(a,e)};h.onerror=function(){I(a,h.error,!0)}};e.onerror=function(b){b.preventDefault();I(a,e.error,!0)}};l.Sa=function(a,b,c){var d=a.a.objectStore(b)["delete"](c);d.onsuccess=function(){I(a,void 0)};d.onerror=function(b){b.preventDefault();I(a,d.error,!0)}};
l.cb=function(a,b,c,d){var e=[],f=a.a.objectStore(b).index(c).openCursor(d),g=0;f.onsuccess=function(b){var c=b.target.result;if(c){var d=c["delete"]();d.onsuccess=function(){g++;c["continue"]()};d.onerror=function(a){e.push(d.error);a.preventDefault();c["continue"]()}}else 0<e.length?I(a,e,!0):I(a,g)};f.onerror=function(b){b.preventDefault();I(a,f.error,!0)}};
l.ya=function(a,b){for(var c=b.length,d=0,e=0;e<c;e++){var f=a.a.objectStore(b[e]).clear();f.onsuccess=function(){d++;d==c&&I(a,d)};f.onerror=function(b){d++;b.preventDefault();d==c&&I(a,f.error,!0)}}};
l.Ea=function(a,b,c){var d=a.a.objectStore(b),e=d.get(c);e.onsuccess=function(b){var c=b.target.result;if(!d.keyPath&&0==d.indexNames.length&&xb&&x(c)&&0<=c.indexOf(";base64,")){'"'==c.charAt(0)&&'"'==c.charAt(c.length-1)&&(c=c.substr(1,c.length-2));c=c.split(";base64,");b=c[0].split(":")[1];for(var c=window.atob(c[1]),e=c.length,k=new Uint8Array(e),m=0;m<e;++m)k[m]=c.charCodeAt(m);I(a,new Blob([k.buffer],{type:b}))}else I(a,b.target.result)};e.onerror=function(b){b.preventDefault();I(a,e.error,!0)}};
l.Wa=function(a,b,c){function d(b){if(null==c[b])if(f++,e[b]=void 0,f==h)I(a,e);else{var m=b+10;m<h&&d(m)}var p;p=g.get(c[b]);p.onsuccess=function(c){f++;e[b]=c.target.result;f==h?I(a,e):(c=b+10,c<h&&d(c))};p.onerror=function(b){f++;b.preventDefault();I(a,p.error,!0)}}var e=[];e.length=c.length;var f=0,g=a.a.objectStore(b),h=c.length;if(0<h)for(b=0;10>b&&b<h;b++)d(b);else I(a,[])};
l.Xa=function(a,b){function c(f){var h=b[f],k=a.a.objectStore(h.b).get(h.a);k.onsuccess=function(h){e++;d[f]=h.target.result;e==b.length?I(a,d):(h=f+10,h<b.length&&c(h))};k.onerror=function(b){e++;b.preventDefault();I(a,k.error,!0)}}var d=[];d.length=b.length;var e=0;if(0<b.length)for(var f=0;10>f&&f<b.length;f++)c(f);else I(a,[])};
l.Ua=function(a,b,c,d){b=a.a.objectStore(b);c&&P(c);var e;null!=d?(d=b.index(d),e=null!=c?d.count(c):d.count()):e=null!=c?b.count(c):b.count();e.onsuccess=function(b){I(a,b.target.result)};e.onerror=function(b){b.preventDefault();I(a,e.error,!0)}};
l.ba=function(a,b,c,d,e,f,g,h,k,m){var p=[],n=a.a.objectStore(c),u=h?k?"prevunique":"prev":k?"nextunique":"next";c=Xb(a)+" "+b+" "+c+(d?":"+d:"")+(e?P(e):"");h&&(c+=" reverse");k&&(c+=" unique");if(m&&r(m[0])){k=d?!r(m[1]):!0;var v=m[0],y=e?e.lower:void 0,A=e?e.upper:void 0,Q=e?!!e.lowerOpen:!1;e=e?!!e.upperOpen:!1;e=mc(h?new L(y,v,Q,k):new L(v,A,k,e));c+=" starting from "+P(m[0]);r(m[1])&&(c+=", "+P(m[1]))}var R;R=1==b||2==b||3==b?d?n.index(d).openKeyCursor(e,u):n.openCursor(e,u):d?n.index(d).openCursor(e,
u):n.openCursor(e,u);var N=!1;R.onsuccess=function(c){if(c=c.target.result){if(!N){if(0<g){N=!0;c.advance(g);return}if(m&&d&&r(m[0]))if(r(m[1])){var e=G.cmp(c.key,m[0]),k=h?-1:1;if(0==e){e=G.cmp(c.primaryKey,m[1]);if(0==e){N=!0;c["continue"]();return}if(e==k)N=!0;else{c["continue"]();return}}else N=!0}else N=!0;else N=!0}1==b?p.push(c.key):2==b?p.push(c.primaryKey):3==b?(k={},d&&(k[d]=c.key),n.keyPath?k[n.keyPath]=c.primaryKey:k._ROWID_=c.primaryKey,p.push(k)):4==b?p.push(c.value):p.push([c.key,c.primaryKey,
c.value]);if(p.length<f)c["continue"]();else m&&(m[0]=lc(c.key),m[1]=lc(c.primaryKey)),I(a,p)}else m&&(m[0]=void 0,m[1]=void 0),I(a,p)};R.onerror=function(b){b.preventDefault();I(a,R.error,!0)}};function Sd(a,b){this.a=b}C(Sd,ge);Sd.prototype.logger=null;Sd.prototype.b=function(a,b,c,d){b=U(this.a,c);return new fe(a,0,b,d)};function he(a,b,c,d){od.call(this,a,0,c,d);this.B=null;this.b=this.f=void 0}C(he,od);l=he.prototype;l.logger=null;l.S=function(){return this.b};l.Na=function(a,b,c,d,e){he.D.Na.call(this,a,b,c,d,e);this.B=x(b)?Jc(this.a,b):null};l.va=function(){return this.v};function ie(a,b){a.f=void 0;a.b=void 0;a.v=void 0;if(r(b))if(B(b)){var c=Bc(b[a.a.g],a.a.type);a.b=c;if(a.g){var d=Jc(a.a,a.i);a.f=Bc(b[a.i],d.type)}else a.f=c;a.v=a.qa?c:je(b,a.a)}else a.v=b}
function ke(a,b,c){Jc(a.a,a.i);var d=[],e=a.i,f=a.V,g=a.f;if(null!=f){var h=f.lower,k=f.upper,m=f.lowerOpen,p=f.upperOpen;a.w?k=null!=k&&-1==K(k,g)?k:g:h=null!=h&&1==K(h,g)?h:g;null!=h&&null!=k?f=pc(h,k,!!m,!!p):f=null!=h?tc.lowerBound(h,!!m):tc.upperBound(k,!!p)}else f=a.w?tc.upperBound(g):tc.lowerBound(g);e=Ic(a.a,d,a.H,e,f,a.w,a.unique);c=a.w?tc.upperBound(c,!1):tc.lowerBound(c,!1);c=Ic(a.a,d,a.H,a.a.g,c,a.w,a.unique);e.o=e.o?e.o+(" AND "+c.o):c.o;c="SELECT "+e.select+" FROM "+e.I+(e.o?" WHERE "+
e.o:"")+(e.group?" GROUP BY "+e.group:"")+" ORDER BY "+e.J;c+=" LIMIT 1";yb(a+": continuePrimary:  SQL: "+c+" : "+P(d));a.m.executeSql(c,d,function(c,d){0<d.rows.length?ie(a,d.rows.item(0)):ie(a);b.call(a,a.f,a.b,a.v);b=null},function(c,d){pd(a,d);ie(a);b.call(a,a.b,a.f,a.v);b=null;return!1})}
function le(a,b,c,d,e,f){var g=!d;d=[];a.g&&null!=f&&null!=c?c=Lc(a.a,a.H,d,a.B.getName(),a.V,c,g,f,a.w,a.unique):null!=c?c=Kc(a.a,a.H,d,a.B?a.B.getName():null,a.V,a.w,a.unique,c,g):(c=Hc(a.a,d,a.H,a.g?a.B.f:a.a.g,a.V,a.w,a.unique),a.g&&(c+=", "+a.a.c+" ASC"));c+=" LIMIT 1";0<e&&(c+=" OFFSET "+e);yb(a+": continue:  SQL: "+c+" : "+P(d));a.m.executeSql(c,d,function(c,d){0<d.rows.length?ie(a,d.rows.item(0)):ie(a);b.call(a,a.f,a.b,a.v);b=null},function(c,d){pd(a,d);ie(a);b.call(a,a.b,a.f,a.v);b=null;
return!1})}l.Ga=function(){return!!this.m};l.update=function(a){if(!this.Ga())throw new Cd;var b=new D,c=this.S();a=Sc(this.a,a,c);var d="REPLACE INTO "+M(this.a)+" ("+a.Ta.join(", ")+") VALUES ("+a.gb.join(", ")+")";yb(this+': update "'+d+'" : '+P(a.values));this.m.executeSql(d,a.values,function(){b.callback(c)},function(a,c){b.l(c);return!1});return b};
l.advance=function(a){var b=this.f,c=this.b,d=!0;null==this.f||this.g&&null==this.b||(--a,d=!1);le(this,function(a,d,g){var h=null!=b&&null!=a&&0==K(b,a);if(this.g){var k=null!=d&&null!=c&&0==K(d,c);if(h&&k)throw new Cb("current: "+b+";"+c+" next: "+a+";"+d);}else if(h)throw new Cb("current: "+b+" next: "+a);this.O(a,d,g)},this.f,d,a,this.b)};l.$=function(a){null!=a?le(this,this.O,a,!0):this.advance(1)};l.openCursor=function(a,b){le(this,this.O,a,!1,0,b)};
l.clear=function(){if(!this.Ga())throw new Cd;var a=new D,b=this.a.g,b="DELETE FROM "+M(this.a)+" WHERE "+b+" = ?",c=[this.S()];yb(this+': clear "'+b+'" : '+P(c));this.m.executeSql(b,c,function(b,c){a.callback(c.rowsAffected)},function(b,c){a.l(c);return!1});return a};l.ua=function(a){var b=K(a,this.b);if(0==b||1==b&&this.w||-1==b&&!this.w)throw new id(this+" to continuePrimaryKey  from "+this.b+" to "+a+" on "+this.L+" direction is wrong");ke(this,this.O,a)};function me(a,b){this.a=b}C(me,Hd);l=me.prototype;l.logger=null;
function je(a,b){if(b.W&&!b.keyPath&&0==b.a.length&&a._default_){var c=a._default_;if(-1==c.indexOf(";base64,"))return Vc(c);'"'==c.charAt(0)&&'"'==c.charAt(c.length-1)&&(c=c.substr(1,c.length-2));for(var d=c.split(";base64,"),c=d[0].split(":")[1],d=window.atob(d[1]),e=d.length,f=new Uint8Array(e),g=0;g<e;++g)f[g]=d.charCodeAt(g);return new Blob([f.buffer],{type:c})}c=a._default_?Vc(a._default_):{};null!=b.keyPath&&(d=Bc(a[b.keyPath],b.type),null!=d&&Rc(b,c,d));for(d=0;d<b.a.length;d++)if(e=b.index(d),
f=e.f,"_default_"!=f&&!e.h&&!e.multiEntry&&("DATE"==e.type||b.W)&&(g=Bc(a[f],e.type),r(g)))for(var f=c,h=0;h<e.b.length;h++)h==e.b.length-1?f[e.b[h]]=g:B(f[e.b[h]])||(f[e.b[h]]={});return c}
l.N=function(a,b,c,d,e,f){function g(b,d){if(null==e[b])if(p++,p==e.length)I(a,m,n);else{var y=b+2;y<e.length&&g(y,d)}var A;A=r(f)?Sc(h,e[b],f[b]):Sc(h,e[b]);y=k+M(h)+" ("+A.Ta.join(", ")+") VALUES ("+A.gb.join(", ")+");";d.executeSql(y,A.values,function(f,y){function N(a,b){var c=k+sa("ydn.db.me:"+h.getName()+":"+a.getName())+" ("+h.c+", "+a.c+") VALUES (?, ?)",e=[wc(O,h.type),wc(b,a.type)];d.executeSql(c,e,function(){},function(){return!1})}p++;var O=r(A.key)?A.key:y.insertId;1>y.rowsAffected&&
(n=!0,O=new Bd(O+" no-op"));for(var T=0,la=h.a.length;T<la;T++){var ib=h.index(T);if(ib.multiEntry)for(var jb=Ib(e[b],ib.keyPath),kb=(jb?jb.length:0)||0,lb=0;lb<kb;lb++)N(ib,jb[lb])}c?I(a,O):(m[b]=O,p==e.length?I(a,m,n):(T=b+2,T<e.length&&g(T,f)))},function(d,f){p++;n=!0;6==f.code&&(f.name="ConstraintError");if(c)I(a,f,!0);else if(m[b]=f,p==e.length)I(a,m,n);else{var h=b+2;h<e.length&&g(h,d)}return!1})}b=!b;var h=U(this.a,d),k=b?"INSERT INTO ":"INSERT OR REPLACE INTO ";d=a.a;var m=[],p=0,n=!1;if(0<
e.length)for(b=0;2>b&&b<e.length;b++)g(b,d);else I(a,[])};
l.bb=function(a,b,c){if(0==c.length)I(a,[]);else{for(var d=[],e=0,f=0,g=this,h=function(h,k){for(var m=[],n=Pc(U(g.a,h)),p=n?void 0:[],u=0;u<k.length;u++)m.push(b[k[u]]),n||p.push(c[k[u]].a);n=Ub(a);ob(n,function(b){for(var c=0;c<k.length;c++)d[k[c]]=b[c];e++;e==f&&I(a,d)},function(){e++;e==f&&I(a,d,!0)});g.N(n,!1,!1,h,m,p)},k="",m=[],p=[],n=0;n<c.length;n++){var u=c[n].b,v=c[n].a;u!=k?(f++,0<m.length&&h(k,m),m=[n],p=[v],k=u):(m.push(n),p.push(v))}0<m.length&&h(k,m)}};
l.Ea=function(a,b,c){var d=a.a,e=U(this.a,b);b=e.c;c=[wc(c,e.type)];b="SELECT * FROM "+M(e)+" WHERE "+b+" = ?";d.executeSql(b,c,function(b,c){if(0<c.rows.length){var d=c.rows.item(0);null!=d?(d=je(d,e),I(a,d)):I(a,void 0)}else I(a,void 0)},function(b,c){I(a,c,!0);return!1})};
l.Wa=function(a,b,c){function d(b,e){var p=h.c,n=[wc(c[b],h.type)],p="SELECT * FROM "+M(h)+" WHERE "+p+" = ?";e.executeSql(p,n,function(e,m){g++;if(0<m.rows.length){var n=m.rows.item(0);null!=n&&(f[b]=je(n,h))}else f[b]=void 0;g==c.length?I(a,f):(n=b+10,n<c.length&&d(n,e))},function(e){g++;if(g==c.length)I(a,f);else{var h=b+10;h<c.length&&d(h,e)}return!1})}var e=a.a,f=[],g=0,h=U(this.a,b);if(0<c.length)for(b=0;10>b&&b<c.length;b++)d(b,e);else I(a,[])};
l.Xa=function(a,b){function c(d,h){var p=b[d],n=U(e.a,p.b),u=kc(p),p=n.c,u=[wc(u,n.type)],p="SELECT * FROM "+M(n)+" WHERE "+p+" = ?";h.executeSql(p,u,function(e,h){g++;if(0<h.rows.length){var m=h.rows.item(0);null!=m&&(f[d]=je(m,n))}else f[d]=void 0;g==b.length?I(a,f):(m=d+10,m<b.length&&c(m,e))},function(b,c){I(a,c,!0);return!1})}var d=a.a,e=this,f=[],g=0;if(0<b.length)for(var h=0;10>h&&h<b.length;h++)c(h,d);else I(a,[])};
l.ya=function(a,b){function c(d,g){function h(a){a="DELETE FROM  "+sa("ydn.db.me:"+k.getName()+":"+a.getName());g.executeSql(a,[])}var k=U(e.a,b[d]),m="DELETE FROM  "+M(k);g.executeSql(m,[],function(e){d==b.length-1?I(a,b.length):c(d+1,e)},function(b,c){I(a,c,!0);return!1});for(var m=0,p=k.a.length;m<p;m++){var n=k.index(m);n.multiEntry&&h(n)}}var d=a.a,e=this;0<b.length?c(0,d):I(a,0)};
l.fb=function(a,b){function c(h){if(h>=b.length)I(a,f,g);else{var k=U(e.a,b[h].b),m=wc(b[h].a,k.type),p=" WHERE "+k.c+" = ?",n="DELETE FROM "+M(k)+p;d.executeSql(n,[m],function(){f++;c(h)},function(){g=!0;c(h);return!1});h++;for(var n=function(a){a="DELETE FROM  "+sa("ydn.db.me:"+k.getName()+":"+a.getName())+p;d.executeSql(a,[m])},u=0,v=k.a.length;u<v;u++){var y=k.index(u);y.multiEntry&&n(y)}}}var d=a.a,e=this,f=0,g=!1;c(0)};
l.Ia=function(a,b,c){function d(a){a="DELETE FROM  "+sa("ydn.db.me:"+f.getName()+":"+a.getName())+h;e.executeSql(a,[g])}var e=a.a,f=U(this.a,b),g=wc(c,f.type),h=" WHERE "+f.c+" = ?";b="DELETE FROM "+M(f)+h;e.executeSql(b,[g],function(b,c){I(a,c.rowsAffected)},function(b,c){I(a,c,!0);return!1});b=0;for(c=f.a.length;b<c;b++){var k=f.index(b);k.multiEntry&&d(k)}};l.Sa=function(a,b,c){ne(this,a,b,void 0,c)};l.eb=function(a,b,c){ne(this,a,b,void 0,c)};l.cb=function(a,b,c,d){ne(this,a,b,c,d)};
function ne(a,b,c,d,e){function f(a){a="DELETE FROM  "+sa("ydn.db.me:"+h.getName()+":"+a.getName())+m;g.executeSql(a,k)}var g=b.a,h=U(a.a,c);a="DELETE FROM "+M(h);c=[];var k=[],m="";null!=e&&(r(d)?(d=Jc(h,d),vc(d.c,d.type,e,k,c)):vc(h.c,h.type,e,k,c),m=" WHERE "+k.join(" AND "));g.executeSql(a+m,c,function(a,c){I(b,c.rowsAffected)},function(a,c){I(b,c,!0);return!1});e=0;for(d=h.a.length;e<d;e++)a=h.index(e),a.multiEntry&&f(a)}
l.Aa=function(a,b){function c(f){var g="SELECT COUNT(*) FROM "+sa(b[f]);d.executeSql(g,[],function(d,g){var m=g.rows.item(0);e[f]=parseInt(m["COUNT(*)"],10);f++;f==b.length?I(a,e):c(f)},function(b,c){I(a,c,!0);return!1})}var d=a.a,e=[];0==b.length?I(a,0):c(0)};l.Ua=function(a,b,c,d,e){var f=[];b=Hc(U(this.a,b),f,6,d,c,!1,e);a.a.executeSql(b,f,function(b,c){var d;a:{if(d=c.rows.item(0))for(var e in d)if(d.hasOwnProperty(e)){d=d[e];break a}d=void 0}I(a,d)},function(b,c){I(a,c,!0);return!1})};
l.ba=function(a,b,c,d,e,f,g,h,k,m){var p=[],n=U(this.a,c),u=n.g,v=n.type,y=v,A=null!=d&&d!==u?Jc(n,d):null,Q=d||u;A&&(y=A.type);c=[];if(m&&r(m[0])){var R=m[0];d=A&&r(m[1])?Lc(n,b,c,A.getName(),e,R,!0,m[1],h,k):Kc(n,b,c,d,e,h,k,R,!0)}else d=Hc(n,c,b,Q,e,h,k);z(f)&&(d+=" LIMIT "+f);z(g)&&(d+=" OFFSET "+g);P(c);a.a.executeSql(d,c,function(c,d){for(var e=d.rows.length,f,g=0;g<e;g++)f=d.rows.item(g),2==b?p[g]=Bc(f[u],v):1==b?p[g]=Bc(f[Q],y):3==b?p[g]=[Bc(f[Q],y),Bc(f[u],v)]:null!=f&&(p[g]=je(f,n));m&&
f&&(m[0]=Bc(f[Q],y),m[1]=Bc(f[u],v));I(a,p)},function(b,c){I(a,c,!0);return!1})};function Td(a,b){this.a=b}C(Td,me);Td.prototype.logger=null;Td.prototype.b=function(a,b,c,d){b=U(this.a,c);return new he(a,0,b,d)};function oe(a,b){this.u=null;this.ia=b||NaN}l=oe.prototype;
l.connect=function(a,b){function c(a,c){for(var d=0;d<b.stores.length;d++)pe(a,c,b.stores[d]);for(var e=a.objectStoreNames,f=e.length,d=0;d<f;d++)bd(b,e[d])||a.deleteObjectStore(e[d])}function d(a,b){f.c||(r(b)?(e.u=null,f.l(b)):(e.u=a,e.u.onabort=function(){},e.u.onerror=function(){},e.u.onversionchange=function(a){if(e.u&&(e.u.onabort=null,e.u.onblocked=null,e.u.onerror=null,e.u.onversionchange=null,!a.defaultPrevented)){e.u.close();e.u=null;var b=Error();b.name=a.type;e.La(b)}},f.callback(parseFloat(g))))}
var e=this,f=new D,g=void 0,h=b.version,k;k=r(h)?G.open(a,h):G.open(a);k.onsuccess=function(f){var h=f.target.result;r(g)||(g=h.version);if(b.b)e.R(function(e){if(b instanceof dd)for(var f=0;f<e.stores.length;f++)bd(b,e.stores[f].getName())||ed(b,e.stores[f].clone());if(0<cd(b,e,!1,!0).length)if(e=z(h.version)?h.version+1:1,"IDBOpenDBRequest"in q){h.close();var g=G.open(a,e);g.onupgradeneeded=function(a){c(a.target.result,g.transaction)};g.onsuccess=function(a){d(a.target.result)};g.onerror=function(){d(null)}}else{var k=
h.setVersion(e+"");k.a=function(a){d(null,a)};k.onsuccess=function(){k.transaction.oncomplete=m;c(h,k.transaction)};var m=function(){var b=G.open(a);b.onsuccess=function(a){d(a.target.result)};b.onerror=function(){d(null)}};null!=k.transaction&&(k.transaction.oncomplete=m)}else d(h)},void 0,h);else if(b.version>h.version){var k=h.setVersion(b.version);k.a=function(a){d(null,a)};k.onsuccess=function(){c(h,k.transaction)}}else e.R(function(a){a=cd(b,a,!1,!0);0<a.length?d(null,new gd("different schema: "+
a)):d(h)},void 0,h)};k.onupgradeneeded=function(a){a=a.target.result;g=NaN;c(a,k.transaction)};k.onerror=function(a){d(null,a)};k.onblocked=function(a){d(null,a)};z(this.ia)&&!isNaN(this.ia)&&setTimeout(function(){"done"!=k.readyState&&d(null,new Gd("connection timeout after "+e.ia))},this.ia);return f};l.ia=18E4;l.La=function(){};l.kb=function(){};l.ab=function(){};l.ib=function(){return"indexeddb"};l.hb=function(){return this.u||null};l.Ka=function(){return!!this.u};l.logger=null;l.u=null;
l.jb=function(){return this.u?parseFloat(this.u.version):void 0};
l.R=function(a,b,c){c=c||this.u;if(r(b)){if(null===b){if(0==c.objectStoreNames.length){a(new $c(c.version));return}throw new fd;}c=b.db}else{b=[];for(var d=c.objectStoreNames.length-1;0<=d;d--)b[d]=c.objectStoreNames[d];if(0==b.length){a(new $c(c.version));return}b=c.transaction(b,Gb)}for(var e=c.objectStoreNames,f=[],g=e.length,d=0;d<g;d++){for(var h=b.objectStore(e[d]),k=[],m=0,p=h.indexNames.length;m<p;m++){var n=h.index(h.indexNames[m]);k[m]=new yc(n.keyPath,void 0,n.unique,n.multiEntry,n.name)}f[d]=
new Fc(h.name,h.keyPath,h.autoIncrement,void 0,k)}b=new $c(c.version,f);a(b)};
function pe(a,b,c){function d(){var b={autoIncrement:!!c.b};null!=c.keyPath&&(b.keyPath=c.keyPath);return a.createObjectStore(c.getName(),b)}if(a.objectStoreNames.contains(c.getName())){b=b.objectStore(c.getName());Dc(c.keyPath||"",b.keyPath||"")?(a.deleteObjectStore(c.getName()),b=d()):ba(b.autoIncrement)&&ba(c.b)&&b.autoIncrement!=c.b&&(a.deleteObjectStore(c.getName()),b=d());for(var e=b.indexNames,f=0;f<c.a.length;f++){var g=c.index(f);!e.contains(g.getName())&&g.g&&b.clear()}for(var h=0,k=0,m=
0,f=0;f<c.a.length;f++){var g=c.index(f),p=!1;if(e.contains(g.getName())){var n=b.index(g.getName()),u=null!=n.unique&&null!=g.unique&&n.unique!=g.unique,v=null!=n.multiEntry&&null!=g.multiEntry&&n.multiEntry!=g.multiEntry,n=null!=n.keyPath&&null!=g.keyPath&&!!Dc(n.keyPath,g.keyPath);if(u||v||n)b.deleteIndex(g.getName()),p=!0,h--,m++}else"BLOB"!=g.type&&(p=!0);p&&(g.unique||g.multiEntry?(p={unique:g.unique,multiEntry:g.multiEntry},b.createIndex(g.getName(),g.keyPath,p)):b.createIndex(g.getName(),
g.keyPath),h++)}for(f=0;f<e.length;f++)Nc(c,e[f])||(b.deleteIndex(e[f]),k++)}else for(b=d(),f=0;f<c.a.length;f++)g=c.index(f),"BLOB"!=g.type&&(g.unique||g.multiEntry?(p={unique:g.unique,multiEntry:g.multiEntry},b.createIndex(g.getName(),g.keyPath,p)):b.createIndex(g.getName(),g.keyPath))}
l.Ca=function(a,b,c,d){var e=this.u;if(!b){b=[];for(var f=e.objectStoreNames.length-1;0<=f;f--)b[f]=e.objectStoreNames[f]}0==b.length?a(null):(b=e.transaction(b,c),b.oncomplete=function(a){d("complete",a)},b.onabort=function(a){d("abort",a)},a(b),a=null)};l.close=function(){this.u.close()};Zb.push(function(a,b){if(!G||b&&"indexeddb"!=b)return null;var c=G.deleteDatabase(a),d=new H("vc");c.onblocked=function(a){Eb(d,a)};c.onerror=function(a){d.l(a)};c.onsuccess=function(a){d.callback(a)};return d});function qe(a,b){this.a=r(a)?a:4194304;this.b=b||"websql"}l=qe.prototype;
l.connect=function(a,b){function c(a,b){var c=a.version?parseInt(a.version,10):0,f=!1,g=0;a.changeVersion(a.version,(b.b?isNaN(c)?1:c+1:b.version)+"",function(c){e.R(function(a){f=!0;for(var d=0;d<b.count();d++){var e=U(a,(b.stores[d]||null).getName()),e=e?Oc(e,b.stores[d]||null):null;re(c,b.stores[d]||null,function(a){a&&g++},e)}for(d=0;d<a.count();d++)e=a.stores[d]||null,bd(b,e.getName())||(b instanceof dd?ed(b,e):(e="DROP TABLE "+M(e),c.executeSql(e,[],function(){},function(a,b){throw b;})))},
c,a)},function(a){throw a;},function(){f&&d(a)})}function d(a,b){r(b)?(e.C=null,g.l(b)):(e.C=a,g.callback(parseFloat(f)))}var e=this,f=NaN,g=new D,h=null;try{"sqlite"==this.b?q.sqlitePlugin?(h=q.sqlitePlugin.openDatabase(a,"",a,this.a),h.readTransaction||(h.readTransaction=h.transaction),h.changeVersion=function(a,b,c,d,e){h.transaction(c,d,e)}):(h=null,this.ra=Error("sqlitePlugin not found.")):h=q.openDatabase(a,"",a,this.a)}catch(k){if("SECURITY_ERR"==k.name)h=null,this.ra=new Fd(k);else throw k;
}h?(f=h.version||"",null!=b.version&&b.version==h.version?d(h):this.R(function(a){cd(b,a,!0,!1)?c(h,b):d(h)},null,h)):d(null,this.ra);return g};l.ib=function(){return this.b};l.ra=null;l.C=null;l.hb=function(){return this.C||null};l.logger=null;l.La=function(){};l.kb=function(){};
function se(a){var b=a.m,c="CREATE TABLE IF NOT EXISTS "+M(a)+" (",d=a.c,c=c+(d+" "+b+" PRIMARY KEY ");a.b&&(c+=" AUTOINCREMENT ");if(!a.W||!a.keyPath&&0==a.a.length)c+=" ,_default_ BLOB";for(var e=[],f=[d],g=0,h=a.a.length;g<h;g++){var k=a.index(g),m="";if(k.multiEntry)m=k.unique?" UNIQUE ":"",k="CREATE TABLE IF NOT EXISTS "+sa("ydn.db.me:"+a.getName()+":"+k.getName())+" ("+d+" "+b+", "+k.c+" "+k.i+m+")",e.push(k);else{k.unique&&(m=" UNIQUE ");var p=k.c;-1==f.indexOf(p)&&(c+=", "+p+" "+k.i+m,f.push(p))}}e.unshift(c+
")");return e}l.jb=function(){return this.C?parseFloat(this.C.version):void 0};
l.R=function(a,b,c){function d(a,b){throw b;}function e(b,c){if(c&&c.rows){for(var d=0;d<c.rows.length;d++){var e=c.rows.item(d);if("__WebKitDatabaseInfoTable__"!=e.name&&"sqlite_sequence"!=e.name&&"table"==e.type){var f="sql"in e?e.sql:void 0,v=f.substr(f.indexOf("("),f.lastIndexOf(")")).match(/(?:"[^"]*"|[^,])+/g),y=void 0,A,f=[],Q=!1,R=!1,N=0;for(;N<v.length;N++){var O=v[N].match(/\w+|"[^"]+"/g),T=va(O,function(a){return a.toUpperCase()}),la=pa(O[0]),O=zc(T[1]);if(-1!=T.indexOf("PRIMARY")&&-1!=
T.indexOf("KEY")){A=O;if(x(la)&&!/^[\s\xa0]*$/.test(la)&&"_ROWID_"!=la){var ib=la.split(","),y=la;1<ib.length&&(y=ib,A=void 0)}-1!=T.indexOf("AUTOINCREMENT")&&(Q=!0)}else if("_ROWID_"!=la)if("_default_"==la)R=!0;else{var jb="UNIQUE"==T[2];0==la.lastIndexOf(e.tbl_name+"-",0)&&(la=la.substr(e.tbl_name.length+1));T=new yc(la,O,jb);f.push(T)}}if(0==e.name.lastIndexOf("ydn.db.me:",0)){var kb=e.name.split(":");if(3<=kb.length){var lb=kb[1],y=new yc(kb[2],O,jb,!0),v=ya(f,function(a){return a.getName()==
kb[2]});0<=v?f[v]=y:f.push(y);v=ya(h,function(a){return a.getName()===lb});0<=v?(y=h[v],h[v]=new Fc(y.getName(),y.keyPath,Q,A,f,void 0,!R)):h.push(new Fc(lb,void 0,!1,void 0,[y]))}}else N=ya(h,function(a){return a.getName()===e.name}),0<=N?(v=h[N].index(0),f.push(v),h[N]=new Fc(e.name,y,Q,A,f,void 0,!R)):(f=new Fc(e.name,y,Q,A,f,void 0,!R),h.push(f))}}d=new $c(g,h);a(d)}}var f=this,g=(c=c||this.C)&&c.version?parseFloat(c.version):void 0,g=isNaN(g)?void 0:g,h=[];b?b.executeSql("SELECT * FROM sqlite_master",
[],e,d):c.readTransaction(function(b){f.R(a,b,c)},function(a){throw a;},e)};function re(a,b,c,d){function e(b){a.executeSql(b,[],function(){f++;f==g.length&&(c(!0),c=null)},function(a,b){f++;f==g.length&&(c(!1),c=null);throw new Ed(b,'"');})}var f=0,g=se(b);if(d){if(0==Tc(b,d).length){c(!0);c=null;return}g.unshift("DROP TABLE IF EXISTS "+sa(b.getName()))}for(b=0;b<g.length;b++)e(g[b])}l.Ka=function(){return!!this.C};l.close=function(){this.C=null};
l.Ca=function(a,b,c,d){function e(a){d("abort",a)}function f(){d("complete",{type:"complete"})}function g(b){a(b)}null===this.C&&(a(null),d("abort",this.ra));c==Gb?this.C.readTransaction(g,e,f):c==Hb?this.C.changeVersion(this.C.version,this.C.version+1+"",g,e,f):this.C.transaction(g,e,f)};
Zb.push(function(a,b){if(ca(q.openDatabase)&&(!b||"websql"==b)){var c=new qe,d=new dd,d=c.connect(a,d),e=function(){};d.A(function(){c.Ca(function(a){a.executeSql('SELECT * FROM sqlite_master WHERE type = "table"',[],function(b,c){if(c&&c.rows)for(var d=c.rows.length,e=0,p=0;p<d;p++){var n=c.rows.item(p);"__WebKitDatabaseInfoTable__"!=n.name&&"sqlite_sequence"!=n.name&&(e++,a.executeSql("DROP TABLE "+n.name))}},function(a,b){throw b;})},[],F,e)});d.Pa(function(){})}});qe.prototype.ab=function(){};/*
 Copyright 2012 YDN Authors, Yathit. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");.
*/
ce.prototype.Ba=function(a){return"indexeddb"==a&&G?new oe(0,this.v):"sqlite"==a&&q.sqlitePlugin?new qe(this.m,"sqlite"):"websql"==a&&ca(q.openDatabase)?new qe(this.m):null};/*
 Copyright 2012 YDN Authors, Yathit. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License");.
*/
ce.prototype.branch=ce.prototype.nb;ce.prototype.getTxNo=ce.prototype.Hb;Rd.prototype.getTxNo=Rd.prototype.g;ce.prototype.run=ce.prototype.wb;Y.prototype.branch=Y.prototype.nb;Y.prototype.add=Y.prototype.add;Y.prototype.addAll=Y.prototype.ka;Y.prototype.get=Y.prototype.get;Y.prototype.keys=Y.prototype.aa;Y.prototype.keysByIndex=Y.prototype.ga;Y.prototype.values=Y.prototype.values;Y.prototype.valuesByIndex=Y.prototype.ja;Y.prototype.put=Y.prototype.put;Y.prototype.putAll=Y.prototype.ta;Y.prototype.clear=Y.prototype.clear;Y.prototype.remove=Y.prototype.wa;Y.prototype.count=Y.prototype.count;X.prototype.add=X.prototype.add;
X.prototype.addAll=X.prototype.ka;X.prototype.get=X.prototype.get;X.prototype.keys=X.prototype.aa;X.prototype.keysByIndex=X.prototype.ga;X.prototype.values=X.prototype.values;X.prototype.valuesByIndex=X.prototype.ja;X.prototype.put=X.prototype.put;X.prototype.putAll=X.prototype.ta;X.prototype.clear=X.prototype.clear;X.prototype.remove=X.prototype.wa;X.prototype.count=X.prototype.count;ka("ydn.db.Key",jc);jc.prototype.id=jc.prototype.rb;jc.prototype.parent=jc.prototype.Ab;jc.prototype.storeName=jc.prototype.Bb;
ka("ydn.db.KeyRange",L);L.upperBound=qc;L.lowerBound=rc;L.bound=pc;L.only=oc;L.starts=sc;fc.prototype.store_name=fc.prototype.b;fc.prototype.getStoreName=fc.prototype.a;function te(a,b,c){Y.call(this,a,b,c)}C(te,ee);ka("ydn.db.Storage",te);function ue(a,b,c){this.db=a;this.b=b;this.type=c||0;this.c=null};function ve(a){zd.call(this,a)}C(ve,zd);
ve.prototype.c=function(a,b){var c=[],d=b[0];if(null==d)return[];for(var e=!0,f=!1,g=d,h=[],k=1;k<a.length;k++)if(null!=b[k]){var m=K(d,b[k]);h[k]=m;this.a?-1==m?e=!1:1==m&&(e=!1,f=!0,-1==K(b[k],g)&&(g=b[k])):1==m?e=!1:-1==m&&(e=!1,f=!0,1==K(b[k],g)&&(g=b[k]))}else e=!1,f=!0;if(e)for(f=0;f<a.length;f++)null!=b[f]&&(c[f]=!0);else if(f)for(f=0;f<a.length;f++)null!=b[f]&&(this.a?-1==K(g,b[f])&&(c[f]=g):1==K(g,b[f])&&(c[f]=g));else for(k=this.a?-1:1,f=1;f<a.length;f++)h[f]===k&&(c[f]=d);return e?(this.b&&
this.b.push(g),c):{continuePrimary:c}};function we(a){zd.call(this,a)}C(we,zd);we.prototype.logger=null;
we.prototype.c=function(a,b){function c(a,b){var c=a.slice(0,a.length-1);c.push(b);return c}function d(a){return a[a.length-1]}var e=[];if(0==a.length||null==a[0]||null==a[0])return[];for(var f=!0,g=0,h=d(a[g]),k=[],m=1;m<a.length;m++)if(null!=a[m]){var p=d(a[m]),n=K(h,p);k[m]=n;this.a?-1==n?f=!1:1==n&&(f=!1,h=p,g=1):1==n?f=!1:-1==n&&(f=!1,h=p,g=1)}else return[];m=this.a?-1:1;if(f){for(f=0;f<a.length;f++)null!=a[f]&&(e[f]=!0);this.b&&this.b.push(b[0]);return e}if(0==g)for(f=1;f<a.length;f++)k[f]==
m&&(e[f]=c(a[f],h));else for(f=0;f<a.length;f++)f!=g&&null!=a[f]&&K(h,d(a[f]))===m&&(e[f]=c(a[f],h));return{"continue":e}};function xe(a,b,c,d){this.c=a;this.a=b||null;this.h=!!c;this.g=!!d;this.b=[];this.f=[]}function ye(a,b){for(var c=b.length-1;0<=c;c--)if(b[c]==a.b[a.b.length-1])b=b.slice(0,c);else break;a.f=b;if(a.a&&a.b[0]){if(a.a.lower!=a.a.upper)throw new Bd("Ordering no allowed with range query");a.a=sc([a.a.lower])}return null}
function ze(a,b){if((0!=a.b.length||0!=a.f.length)&&Ae(a)&&!Be(a))throw new Bd('Require index "'+a.b.concat(a.f).join(", ")+'" not found in store "'+a.c.getName()+'"');var c=new td(a.c.getName(),Ce(a),a.a,a.h,a.g,!!b);c.s=a.b.length;return c}xe.prototype.clone=function(){var a=new xe(this.c,this.a,this.h,this.g);a.f=this.f.slice();a.b=this.b.slice();return a};function Be(a){var b=a.b.concat(a.f),c=Mc(a.c,b);return c||b[b.length-1]==a.c.keyPath&&(c=Mc(a.c,b.slice(0,b.length-1)))?c:null}
function Ce(a){return(a=Be(a))?a.getName():void 0}xe.prototype.unique=function(a){var b=this.clone();b.g=!!a;return b};function Ae(a){return 0<a.b.length?!0:1==a.f.length?a.f[0]!=a.c.keyPath:1<a.f.length?!0:!1}
xe.prototype.o=function(a,b,c,d,e){c=xc(b,c,d,e);if(0<this.b.length)if(this.a)if(null!=this.a.lower&&null!=this.a.upper&&0==K(this.a.lower,this.a.upper))a=t(this.a.lower)?this.a.lower.slice().push(b):[this.a.lower,b],d=null!=d?d:"\uffff",c=t(this.a.upper)?this.a.upper.slice().push(d):[this.a.upper,d],this.a=xc(b,a,d,c);else if(1==this.b.length&&this.b[0]==a||t(a)&&Ca(this.b,a))this.a=uc(this.a,c);else return"cannot use where clause with existing filter";else return"cannot use where clause with existing filter";
else this.b=t(a)?a:[a],this.a=this.a?uc(this.a,c):c;return null};function De(a,b,c,d){ue.call(this,a,b,c);this.a=d}C(De,ue);De.prototype.open=function(){var a={push:function(){}},a=Ee(this)?new we(a):new ve(a);return Xd(this.db,a,Fe(this))};function Fe(a){for(var b=[],c=0;c<a.a.length;c++)b[c]=ze(a.a[c]);return b}function Ee(a){for(var b=0;b<a.a.length;b++)if(0<a.a[b].b.length)return!0;return!1}De.prototype.Fa=function(){return this.a.slice()};De.prototype.select=function(){throw Error("not impl");};function Z(a,b,c,d){ue.call(this,a,b,c);this.a=d}C(Z,ue);l=Z.prototype;l.Cb=function(){return new Z(this.db,this.b,this.type,this.a.clone())};l.Eb=function(){var a=this.a,b=a.clone();b.h=!a.h;return new Z(this.db,this.b,this.type,b)};l.unique=function(a){if(!ba(a))throw new E("unique value must be a boolean, but "+typeof a+" found");a=this.a.unique(a);return new Z(this.db,this.b,this.type,a)};
l.J=function(a){var b=x(a)?[a]:a;a=this.a.clone();if(b=ye(a,b))throw Error(b);return new Z(this.db,this.b,this.type,a)};
l.o=function(a,b,c,d,e){if(Ce(this.a)&&Ce(this.a)!=a){var f=xc(b,c,d,e),f=new xe(U(this.b,this.a.c.getName()),f,this.a.h,this.a.g),f=(new Z(this.db,this.b,this.type,f)).Fa().concat(this.Fa());return new De(this.db,this.b,this.type,f)}if(!Ce(this.a)&&!Nc(U(this.b,this.a.c.getName()),a))throw new E('index "'+a+'" not exists in '+this.a.c.getName());f=this.a.clone();if(a=f.o(a,b,c,d,e))throw new E(a);return new Z(this.db,this.b,this.type,f)};
l.select=function(a){var b=U(this.b,this.a.c.getName()),c=x(a)?[a]:a,d=this.type;a=this.a.clone();d=Ce(this.a);if(1==c.length)if(d=c[0],"_ROWID_"==d||d==b.keyPath)d=2;else if(d&&"*"!=d)if(Nc(b,d)){if(b=ye(a,c))throw new E(b);d=1}else throw new E('Invalid select "'+d+'", index not found in store "'+b.getName()+'"');else d=4;else if(2==c.length){if(!d)throw new E("Only primary key can be selected for this query.");for(var e=0;2>e;e++){var f;if(f="_ROWID_"!=c[e]){f=b;var g=c[e];f=!(r(f.keyPath)&&(1==
f.h.length?f.keyPath===g:w(g)&&Ca(f.h,g)))}if(f&&c[e]!=d)throw new E('select field name must be "'+d+'", but "'+c[e]+'" found.');}d=3}else throw new E("Selecting more than 2 field names is not supported, but "+c.length+" fields selected.");return new Z(this.db,this.b,d,a)};l.Db=function(a){a=a||100;var b=4,c=Ge(this);this.c&&this.c[0]&&(c=xd(c,this.c[0],this.c[1]));if(2==this.type||3==this.type||1==this.type)b=this.type;a=Yd(this.db,b,c,a);a.A(function(){"rest"==c.g&&(this.c=[c.i,c.j])},this);return a};
l.Fa=function(){return[this.a.clone()]};function Ge(a){return ze(a.a,!(2==a.type||3==a.type||1==a.type))}l.vb=function(a,b){var c=Ge(this);c.c&&(c=new td(c.b,c.f,c.a,vd(c),wd(c),!1,c.m));var d=this.db.open(function(c){var f=c.va();if(x(a))Jb(f,a,b);else if(t(a))for(var g=0;g<a.length;g++)Jb(f,a[g],b[g]);else if(B(a))for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);pb(d,c.update(f))},c,F,this);return d};l.open=function(a,b){return this.db.open(a,Ge(this),F,b)};
l.count=function(){return Ae(this.a)?this.a.g?this.db.count(ze(this.a)):this.db.count(this.a.c.getName(),Ce(this.a),this.a.a):this.db.count(this.a.c.getName(),this.a.a)};l.clear=function(){return Ae(this.a)?this.db.clear(this.a.c.getName(),Ce(this.a),this.a.a):this.db.clear(this.a.c.getName(),this.a.a)};
ee.prototype.I=function(a,b,c,d,e){if(!bd(this.c,a))throw new E('Store "'+a+'" not found.');var f=null;if(r(b)){if(!r(c))throw new E("boundary value must be defined.");f=xc(b,c,d,e)}else if(r(d))throw new E("second boundary must not be defined.");a=new xe(U(this.c,a),f);return new Z(this.b,this.c,null,a)};
Vd.prototype.I=function(a,b,c,d,e){if(!bd(this.b,a))throw new E('Store "'+a+'" not found.');var f=null;if(r(b)){if(!r(c))throw new E("boundary value must be defined.");f=xc(b,c,d,e)}else if(r(d))throw new E("second boundary must not be defined.");a=new xe(U(this.b,a),f);return new Z(this,this.b,null,a)};Z.prototype.copy=Z.prototype.Cb;Z.prototype.count=Z.prototype.count;Z.prototype.list=Z.prototype.Db;Z.prototype.order=Z.prototype.J;Z.prototype.patch=Z.prototype.vb;Z.prototype.reverse=Z.prototype.Eb;Z.prototype.unique=Z.prototype.unique;Z.prototype.where=Z.prototype.o;ee.prototype.from=ee.prototype.I;Vd.prototype.from=Vd.prototype.I;

//# sourceMappingURL=ydn.db-is-core-qry.js.map
return ydn;}, (this || {}));
